---
title: "JMbdirect"
output: 
  flexdashboard::flex_dashboard:
  social: menu
source_code: embeded
runtime: shiny    
---
  
  
  
```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(jmBIG)
library(survival)
library(dplyr)
library(jmBIG)
library(JMbdirect)
library(ggplot2)
library(FastJM)
library(JMbayes2)
library(lme4)
library(rstanarm)
library(joineRML)
library(DT)
library(shinycssloaders)
#https://drive.google.com/file/d/1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3/view?usp=sharing
#
```




```{r}

st_pbcid<-function(){
  new_pbcid<-pbc2.id
  new_pbcid$time_2<-rexp(n=nrow(pbc2.id),1/10)
  cen_time<-runif(nrow(pbc2.id),min(new_pbcid$time_2),max(new_pbcid$time_2))
  status_2<-ifelse(new_pbcid$time_2<cen_time,1,0)
  new_pbcid$status_2<-status_2
  new_pbcid$time_2<-ifelse(new_pbcid$time_2<cen_time,new_pbcid$time_2,cen_time)
  new_pbcid$time_2<-ifelse(new_pbcid$time_2<new_pbcid$years,new_pbcid$years,new_pbcid$time_2)
  new_pbcid
}
new_pbc2id<-st_pbcid()
pbc2$status_2<-rep(new_pbc2id$status_2,times=data.frame(table(pbc2$id))$Freq)
pbc2$time_2<-rep(new_pbc2id$time_2,times=data.frame(table(pbc2$id))$Freq)

simulated_ldata<-pbc2
simulated_sdata<-new_pbc2id
simulated_ldata$id<-as.numeric(as.character(simulated_ldata$id))
simulated_sdata$id<-as.numeric(as.character(simulated_sdata$id))
simulated_ldata<-simulated_ldata[simulated_ldata$id<=100,]
simulated_sdata<-simulated_sdata[simulated_sdata$id<=100,]
```


Introduction
=====================================  
  
  Column {data-width=1000}
-------------------------------------

```{r}
shinyApp(
  ui_page1 <- fluidPage(
    tags$style(HTML("
      body { background-color: #f0f8ff; }
      .main-title { color: darkblue; font-size: 30px; font-weight: bold; text-align: center; }
      .summary-text { color: blue; }
      .plot-title { color: darkred; font-size: 30px; font-weight: bold; text-align: center; }
.sidebar-label {
  color: darkred;
  font-weight: bold !important;
  font-size: 15px;
  padding: 12px;
  text-align: center;
}
      .control-label, .shiny-options-group label { color: darkred; font-size: 16px; font-weight: bold; }
      .sidebar-input select { color: darkgreen; font-weight: bold; }
      .well { background-color: #e6f2ff; border-radius: 10px; }
      .main-panel { background-color: #ffffff; padding: 20px; border-radius: 10px; }
      .custom-text-output {
        color: rgb(0, 70, 0);
        font-size: 30px;
        font-family: 'Times New Roman', Times, serif;
        background-color: #f4f4f4;
        padding: 10px;
        border-radius: 5px;
      }
    ")),

    titlePanel(div("JMbdirect: Joint Model for Longitudinal and Multiple Time-to-Events Data", class = "main-title")),

    sidebarLayout(
      sidebarPanel(

        h3("Developed by:"),
        div(h5(span("Atanu Bhattacharjee", class = "sidebar-label"))),
        div(h5(span("Bhrigu Kumar Rajbongshi", class = "sidebar-label"))),
        div(h5(span("Gajendra K Vishwakarma", class = "sidebar-label"))),
         p("Download the JMbdirect package from:"),
        a("CRAN - JMbdirect", href = "https://cran.r-project.org/web/packages/JMbdirect/index.html")
      ),

      mainPanel(
        div(h3("Introduction"), class = "plot-title"),
        p("Joint models are statistical frameworks that simultaneously analyze longitudinal and time-to-event data. They are particularly useful in medical research where repeated measurements of a biomarker are linked to survival outcomes."),
        #div(style = "float: right; margin-left: 10px;", imageOutput("image_output_page1")),
        div(
          style = "float: right; margin-left: 10px; text-align: center;",
          h6(
            "Fig: The figure shows the longitudinal and survival plots", br(),
            "for Subject ID: 1 to 100",
            style = "color: darkred; font-weight: bold; font-style: italic;"
          ),
          imageOutput("image_output_page1")
        ),

        p("This shinny app provides an user friendly interface to use our newly developed R package JMbdirect, which is  designed for fitting joint models to longitudinal and multiple time-to-events data. It provides functions for model fitting, prediction, and visualization."),
        p("A typical joint model consists of two submodels:"),
        tags$ul(
          tags$li("A longitudinal submodel for repeated measures: ",
                  tags$br(),
                  withMathJax("$$y_i(t) = X_i(t)\\beta + Z_i(t)b_i + \\epsilon_i(t)$$")),
          tags$li("A survival submodel for time-to-event data: ",
                  tags$br(),
                  withMathJax("$$h_i(t) = h_0(t)\\exp(W_i\\gamma + \\alpha m_i(t))$$"))
        ),

        h4("Explanation of Model Terms"),
        tags$ul(
          tags$li("\\( y_i(t) \\): Observed repeated biomarker measurement for individual \\( i \\) at time \\( t \\)."),
          tags$li("\\( X_i(t) \\): Fixed-effect covariates (e.g., treatment, age)."),
          tags$li("\\( \\beta \\): Regression coefficients for the fixed effects."),
          tags$li("\\( Z_i(t) \\): Random-effect covariates (often a subset of \\( X_i(t) \\))."),
          tags$li("\\( b_i \\): Individual-specific random effects."),
          tags$li("\\( \\varepsilon_i(t) \\): Error term, assumed to be normally distributed."),
          tags$li("\\( h_i(t) \\): Hazard function for individual \\( i \\) at time \\( t \\) (the risk of experiencing an event)."),
          tags$li("\\( h_0(t) \\): Baseline hazard function."),
          tags$li("\\( W_i \\): Survival-related covariates (e.g., age, treatment group)."),
          tags$li("\\( \\gamma \\): Regression coefficients for survival covariates."),
          tags$li("\\( \\alpha \\): Association parameter linking the longitudinal and survival processes."),
          tags$li("\\( m_i(t) \\): Predicted mean trajectory from the longitudinal model.")
        ),

        #h4("Usage"),
        #p("Here is an example of fitting a joint model using JMbdirect:"),
        #pre(code("library(JMbdirect)\nfit <- jmb_direct(long_data, surv_data, formula = list(fixed = y ~ time + treatment, random = ~ time | id), id_var = 'id')\nsummary(fit)")),

        h4("Example Datasets"),
        DT::DTOutput("exampledatalong"),
        DT::DTOutput("exampledatasurv")
      )
    )
  ),
  server_page1 <- function(input, output, session) {

    temp_file <- tempfile(fileext = ".gif")

    # Step 2: Download the file from Google Drive
    gif_url <- "https://drive.google.com/uc?id=1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3"

    download.file(gif_url, temp_file, mode = "wb")  # Save as binary file
    output$image_output_page1 <- renderImage({
      list(
        src = temp_file,
        contentType = "image/gif",
        width = 410,
        height = 350
      )
    }, deleteFile = FALSE)  # Don't delete immediately, we'll do it manually




    output$exampledatalong <- DT::renderDT({
      data_long <- as.data.frame(new_long2[new_long2$id < 4, ])
      numeric_cols <- sapply(data_long, is.numeric)
      data_long[numeric_cols] <- lapply(data_long[numeric_cols], round, 1)
      DT::datatable(data_long, options = list(pageLength =10, autoWidth = TRUE, dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'print'), scrollX = TRUE, scrollY = "150px",scrollCollapse = TRUE, paging = TRUE), class = "cell-border stripe hover", width = "100%", height = "100px") %>%
        DT::formatStyle(columns = names(data_long), color = "darkred", backgroundColor = "#f0f8ff", fontSize = '10px')
    })

    output$exampledatasurv <- DT::renderDT({
      data_surv <- as.data.frame(new_surv2[new_surv2$id < 5, ])
      numeric_cols <- sapply(data_surv, is.numeric)
      data_surv[numeric_cols] <- lapply(data_surv[numeric_cols], round, 1)
      DT::datatable(data_surv, options = list(pageLength = 3, autoWidth = TRUE, dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'print'), scrollX = TRUE, scrollY = "150px",scrollCollapse = TRUE, paging = TRUE), class = "cell-border stripe hover", width = "100%", height = "100px") %>%
        DT::formatStyle(columns = names(data_surv), color = "darkred", backgroundColor = "#f0f8ff", fontSize = '10px')
    })
  },
  options = list(height=1000,width="100%")
)
```


jmbB
=====================================  
  
  Column {data-width=1000}
-------------------------------------

```{r}

shinyApp(
ui_page2<-fluidPage(
  tags$style(HTML("
    /* Change entire page background */
    body { background-color: #f0f8ff; } /* Light blue */

    /* Style for the main title */
    .main-title { color: darkblue; font-size: 28px; font-weight: bold; text-align: center; }

    /* Styling for different text elements */
    .summary-text { color: blue; }
    .plot-title { color: darkred; font-size: 20px; font-weight: bold; }

    /* Change color of sidebar panel text */
    .sidebar-label { color: blue; font-weight: bold; }

    /* Change color of all sidebar input labels */
    .control-label, .shiny-options-group label { color: darkred; font-size: 16px; font-weight: bold; }

    /* Style for select input dropdown */
    .sidebar-input select { color: darkgreen; font-weight: bold; }

    /* Change color of action button text */
    #submit_page2 { background-color: white; color: red; border: 2px solid red; font-weight: bold; }

    /* OPTIONAL: Add hover effect to the submit button */
    #submit_page2:hover { background-color: red; color: white; }

    /* Customize sidebar background */
    .well { background-color: #e6f2ff; border-radius: 10px; } /* Light blue */

    /* Customize main panel background */
    .main-panel { background-color: #ffffff; padding: 20px; border-radius: 10px; }

      .custom-text-output {
      color: rgb(0, 70, 0);  /* Change text color */
      font-size: 15px;   /* Adjust font size */
      font-family: 'Times New Roman', Times, serif;/* Use monospace font */
      background-color: #f4f4f4; /* Light gray background */
      padding: 10px; /* Add padding */
      border-radius: 5px; /* Rounded corners */
      }
    /* Change text color inside text input fields */
    .form-control {
      color: darkred !important; /* Change text color */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Change text color inside all selectInput dropdowns */
    .selectize-input {
      color: darkred !important;  /* Change dropdown text color */
      font-weight: bold !important;
      font-size: 16px !important;
      /*background-color: lightgray !important;  Change background */
      /*border: 2px solid red !important;   Change border color */
    }

    /* Change text color inside the dropdown list */
    .selectize-dropdown-content {
      color: darkred !important; /* Change dropdown option text */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Hover effect for dropdown options */
    .selectize-dropdown-content .option:hover {
      background-color: yellow !important;  /* Change hover background */
      color: black !important;  /* Change text color on hover */
    }

    /* Custom styling for the DT table */
    .styled-table .dataTable {
        border-collapse: collapse;
        width: 40%;
        font-size: 6px;
        border: 1px solid #ddd;
    }

    /* Header styling */
    .styled-table .dataTable thead {
        background-color: darkblue;
        color: white;
    }

    /* Row hover effect */
    .styled-table .dataTable tbody tr:hover {
        background-color: #e6f2ff; /* Light blue */
    }

    /* Border for table */
    .styled-table .dataTable tbody td {
        border: 1px solid #ddd;
        padding: 5px;
    }

    .gif-container {
  display: flex;
  justify-content: flex-end; /* Center horizontally */
  align-items: center; /* Center vertically (if needed) */
  margin-top: 20px;
  padding: 10px; /* Add some space inside */
  border: 3px solid #3498db; /* Blue border */
  border-radius: 10px; /* Rounded corners */
  background-color: #f9f9f9; /* Light background */
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1); /* Soft shadow */
  width: 420px; /* Box width slightly larger than GIF */
  height: 410px; /* Box height */
}

.gif-container img {
  width: 400px;  /* Adjust size */
  height: auto;
}
")),
  #titlePanel(tags$h1("Linear Regression in Shiny", class = "main-title"))
  titlePanel(tags$h1("Joint Model for longitudinal and multiple time-to-events data using jmbB() function",class="main-title")),
  sidebarLayout(
    sidebarPanel(
      radioButtons("data_option_page2", span("Select data source:",class="sidebar-label"),
                   c("Upload my own dataset"= "upload",
                     "Use default dataset" = "default")),
      conditionalPanel(
        condition = "input.data_option_page2== 'default' && input.Bigdata_page2=='No'",
        sliderInput("pid_page2", span("Select ID No. :",class="sidebar-label"), min = min(simulated_sdata$id), max = 100, value = 50)
      ),

      conditionalPanel(
        condition = "input.data_option_page2== 'default' && input.Bigdata_page2=='Yes'",
        sliderInput("pidBIG_page2", span("Select ID No. :",class="sidebar-label"), min = min(new_surv2$id), max = 600, value = 10)
      ),


      conditionalPanel(
        condition = "input.data_option_page2 == 'upload'",
        fileInput("lfile_page2", span("Upload Longitudinal Data (CSV format)",class="sidebar-label")),
        fileInput("sfile_page2", span("Upload Survival Data (CSV format)",class="sidebar-label")),
        uiOutput("pid_slider_upload_page2")
      ),
      selectInput("Bigdata_page2", span("Is the sample size geater than 500?",class="sidebar-label"), choices =c("Yes","No")),
      selectInput("idvar_page2", span("ID variable",class="sidebar-label"), choices =NULL),
      selectInput("timevar_page2", span("Visit time",class="sidebar-label"), choices = NULL),


      textInput("longmodel1_page2", span("Longitudinal data model (For event 1)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel1_page2", span("Longitudinal data model random effect part (For event 1)",class="sidebar-label"), value = "~visit|id"),

      textInput("longmodel2_page2", span("Longitudinal data model (For event 2)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel2_page2", span("Longitudinal data model random effect part (For event 2)",class="sidebar-label"), value = "~visit|id"),
      textInput("survmodel1_page2", span("Survival data model (For event 1)",class="sidebar-label"), value = "Surv(time,status)~x1+visit"),
      textInput("survmodel2_page2", span("Survival data model (For event 2)",class="sidebar-label"), value = "Surv(time_2,status_2)~x1+visit"),
      textInput("time_points1_page2",span("Time points for plot (event 1):",class="sidebar-label"),value=4),
      textInput("time_points2_page2",span("Time points for plot (event 2):",class="sidebar-label"),value=9),
      numericInput("nchain_page2", span("Number of chain for MCMC",class="sidebar-label"), value = 1),

      numericInput("samplesize_page2", span("Loop size",class="sidebar-label"), value = 200),
      actionButton("submit_page2", span("Submit",class="submit_page2"))
    ),

    mainPanel(
      #tags$img(src = "jmbdirect_animation.gif", height = "400px", width = "400px"),
      # div(
      #   class = "gif-container",
      #   tags$img(src = "C://rproject/JmbdirectApp/jmbdirect_animation.gif", width = "500px", height = "500px")
      # ),
      
      p('jmbB(): a function for joint model in small data as well as BIG DATA using JMbayes2, jmBIG package. For more information about the arguments of the function please look ',a("here.",href = "https://cran.r-project.org/web/packages/JMbdirect/index.html")),
      div(
           style = "margin-left: 90px; text-align: center;",
          h6(
            "Fig: The figure shows the longitudinal and survival plots", br(),
            "for Subject ID: 1 to 100",
            style = "color: darkred; font-weight: bold; font-style: italic;"
          ),
          imageOutput("image_output_page2"),
          
        ),
      
      
      h4(strong("An example R Code for the model:"),class="summary-text"),
      div(class = "custom-text-output",uiOutput("rCode_page2")),
      h4(strong("Model summary:"),class="summary-text"),
      div(verbatimTextOutput("summarymodel_page2"),class = "custom-text-output"),
      h4(strong("Selected ID information:"),class="summary-text"),
      div(textOutput("selected_var_page2"),class= "custom-text-output"),
      div(dataTableOutput('longID_page2'),class="custom-text-output"),
      h4(strong("Plot for the selected ID:"),class="summary-text"),
      div(textOutput("selectedID_page2"),class="custom-text-output"),
      shinycssloaders::withSpinner(plotOutput("summaryplot_page2"))


    )
  )
),
server_page2<-function(input, output, session){
  
  
  temp_file <- tempfile(fileext = ".gif")
  
  # Step 2: Download the file from Google Drive
  gif_url <- "https://drive.google.com/uc?id=1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3"
  
  download.file(gif_url, temp_file, mode = "wb")  # Save as binary file
  output$image_output_page2 <- renderImage({
    list(
      src = temp_file,
      contentType = "image/gif",
      width = 410,
      height = 350
    )
  }, deleteFile = FALSE)  # Don't delete immediately, we'll do it manually

  
  output$rCode_page2 <- renderUI({
  HTML("model_jmbBdirect<-jmbB(dtlong=...,dtsurv=....,<br>
  longm=list(serBilir~drug*year,serBilir~drug*year),<br>
  survm=list(Surv(years,status2)~drug,Surv(time_2,status_2)~drug+age),<br>
  rd=list(~year|id,~year|id),id='id',timeVar='year')<br><br>

  <b>Here is the list of entries in sidebar panel according to this example (default small data):</b><br>
  ID variable: id<br>
  Visit time: year<br>
  Longitudinal data model (For event 1): serBilir~drug*year<br>
  Longitudinal data model random effect part (For event 1): ~year|id<br>
  Longitudinal data model (For event 2): serBilir~drug*year<br>
  Longitudinal data model random effect part (For event 2): ~year|id<br>
  Survival data model (For event 1): Surv(years,status2)~drug<br>
  Survival data model (For event 2): Surv(time_2,status_2)~drug+age<br>
  Time points for plot (event 1): 6<br>
  Time points for plot (event 2): 10<br>
  Is it BIG data: No<br>
  Loop size: 200 (default you may use other also)")
  })


  defaultsurvdata_page2 <- reactive({
    #req(input$data_option_page2)
    if (input$data_option_page2 == 'upload') {
      req(input$sfile_page2)
      defaultsurvdata_page2 <- read.csv(input$sfile_page2$datapath)
    } else {
      req(input$Bigdata_page2)
      if(input$Bigdata_page2=="Yes"){
        defaultsurvdata_page2 <- new_surv2[new_surv2$id<=600,]
      }else{
        defaultsurvdata_page2 <- simulated_sdata
      }
    }
    return(defaultsurvdata_page2)
  })


  observeEvent(defaultsurvdata_page2(), {
    updateSelectInput(session, "idvar_page2", choices = names(defaultsurvdata_page2()))
    updateSelectInput(session, "timevar_page2", choices = names(defaultsurvdata_page2()))
    updateSelectInput(session, "event_page2", choices = names(defaultsurvdata_page2()))
    updateSelectInput(session, "obs_time_page2", choices = names(defaultsurvdata_page2()))
  })


  defaultlongdata_page2 <- reactive({
    if (input$data_option_page2 == 'upload') {
      req(input$lfile_page2)
      #req(input$data_option_page2)
      defaultlongdata_page2 <- read.csv(input$lfile_page2$datapath)
    } else {
      req(input$Bigdata_page2)
      if(input$Bigdata_page2=="Yes"){
        defaultlongdata_page2 <- new_long2[new_long2$id<=600,]
      }else{
        defaultlongdata_page2 <- simulated_ldata
      }
    }
    return(defaultlongdata_page2)
  })


  output$pid_slider_upload_page2 <- renderUI({
    req(input$idvar_page2)
    tagList(
      selectInput("pid_page22", "Patient ID", choices=defaultsurvdata_page2()[[input$idvar_page2]],selectize = FALSE,size=5)
    )
  })

  output$selected_var_page2 <- reactive({

    if (input$data_option_page2 == "default") {
      req(input$pid_page2)
      req(input$Bigdata_page2)
      if(input$Bigdata_page2=="Yes"){
        req(input$pidBIG_page2)
        paste("You have selected patient ID", input$pidBIG_page2)
      }else{
        paste("You have selected patient ID", input$pid_page2)
      }
    } else {
      req(input$pid_page22)
      paste("Uploaded data selected with patient ID",input$pid_page22)
    }
  })

  output$selectedID_page2 <- reactive({

    if (input$data_option_page2 == "default") {
      req(input$pid_page2)
      req(input$Bigdata_page2)
      if(input$Bigdata_page2=="No"){
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmbB() for the selected patient ID: ',input$pid_page2)
      }else{
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmbB() for the selected patient ID: ',input$pidBIG_page2)
      }
    } else {
      req(input$pid_page22)
      paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmbB() for the selected patient ID: ',input$pid_page22)
    }
  })


  rv<-reactiveValues(model_page2=NULL,idnum_page2=NULL)

  longID_page2 <- reactive({

    if (input$data_option_page2 == "default") {
      req(input$pid_page2)
      req(input$timevar_page2)
      req(input$idvar_page2)
      req(defaultlongdata_page2())
      req(defaultsurvdata_page2())

      surv_var1_page2<-all.vars(as.formula(input$survmodel1_page2))
      surv_var2_page2<-all.vars(as.formula(input$survmodel2_page2))
      surv_status1_page2<-surv_var1_page2[2]
      surv_status2_page2<-surv_var2_page2[2]
      surv_time1_page2<-surv_var1_page2[1]
      surv_time2_page2<-surv_var2_page2[1]

      long_data_page2<-defaultlongdata_page2()
      surv_data_page2<-defaultsurvdata_page2()
      rv$idnum_page2<-if(input$Bigdata_page2=='No'){input$pid_page2}else{input$pidBIG_page2}
      newdata_page2<-long_data_page2[long_data_page2[[input$idvar_page2]]==rv$idnum_page2,]
      newdata_page2

    } else {
      req(input$timevar_page2)
      req(input$idvar_page2)
      req(defaultlongdata_page2())
      req(defaultsurvdata_page2())
      req(input$pid_page22)
      surv_var1_page2<-all.vars(as.formula(input$survmodel1_page2))
      surv_var2_page2<-all.vars(as.formula(input$survmodel2_page2))
      surv_status1_page2<-surv_var1_page2[2]
      surv_status2_page2<-surv_var2_page2[2]
      surv_time1_page2<-surv_var1_page2[1]
      surv_time2_page2<-surv_var2_page2[1]

      long_data_page2<-defaultlongdata_page2()
      surv_data_page2<-defaultsurvdata_page2()
      rv$idnum_page2<-input$pid_page22
      newdata_page2<-long_data_page2[long_data_page2[[input$idvar_page2]]==input$pid_page22,]
      newdata_page2
      }
  })


  observeEvent(input$submit_page2, {
    output$longID_page2 <- DT::renderDT({
      data_page2 <- as.data.frame(longID_page2())

      # Round numeric columns to 1 decimal place
      numeric_cols <- sapply(data_page2, is.numeric)
      data_page2[numeric_cols] <- lapply(data_page2[numeric_cols], round, 1)

      DT::datatable(data_page2,
                    options = list(
                      pageLength = 5,
                      autoWidth = TRUE,
                      dom = 'Bfrtip',
                      buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),  # Export options
                      scrollX = TRUE,  # Enable horizontal scrolling
                      scrollY = "400px",
                      scrollCollapse = TRUE,# Enable vertical scrolling with fixed height
                      paging = TRUE  # Keep pagination enabled
                    ),
                    class = "cell-border stripe hover",
                    width = "100%",  # Adjust table width
                    height = "500px"  # Adjust table height
      ) %>%
        DT::formatStyle(
          columns = names(data_page2),
          color = "black",
          backgroundColor = "#f0f8ff",  # Light blue
          fontSize = '10px'  # Change font size
        )
    })
  })




  observeEvent(input$submit_page2,{
    output$summarymodel_page2 <- renderPrint({
      req(input$longmodel1_page2)
      req(input$longmodel2_page2)
      req(input$rdmodel1_page2)
      req(input$rdmodel2_page2)
      req(input$survmodel1_page2)
      req(input$survmodel2_page2)
      req(input$timevar_page2)
      req(input$idvar_page2)
      req(input$Bigdata_page2)
      req(defaultlongdata_page2())
      req(defaultsurvdata_page2())

      longmodel1_page2<-as.formula(input$longmodel1_page2)
      rdmodel1_page2<-as.formula(input$rdmodel1_page2)
      longmodel2_page2<-as.formula(input$longmodel2_page2)
      rdmodel2_page2<-as.formula(input$rdmodel2_page2)
      survmodel1_page2<-as.formula(input$survmodel1_page2)
      survmodel2_page2<-as.formula(input$survmodel2_page2)
      BIGdata_t<-ifelse(input$Bigdata_page2=="Yes",TRUE,FALSE)
      long_data_page2<-defaultlongdata_page2()
      surv_data_page2<-defaultsurvdata_page2()

      fitmodel_page22 <-jmbB(dtlong=long_data_page2,
                             dtsurv=surv_data_page2,
                             longm=list(longmodel1_page2,longmodel2_page2),
                             survm=list(survmodel1_page2, survmodel2_page2),
                             rd=list(rdmodel1_page2,rdmodel2_page2),
                             timeVar=input$timevar_page2,
                             nchain=1,
                             samplesize =200,
                             BIGdata=BIGdata_t,
                             id=input$idvar_page2)

      rv$model_page2<-fitmodel_page22
      fitmodel_page22

    })
  })



  observeEvent(input$submit_page2,{
    output$summaryplot_page2<- renderPlot({

      req(input$timevar_page2)
      req(input$idvar_page2)
      req(defaultlongdata_page2())
      req(defaultsurvdata_page2())
      req(input$time_points1_page2)
      req(input$time_points2_page2)

      surv_var1_page2<-all.vars(as.formula(input$survmodel1_page2))
      surv_var2_page2<-all.vars(as.formula(input$survmodel2_page2))
      surv_status1_page2<-surv_var1_page2[2]
      surv_status2_page2<-surv_var2_page2[2]
      surv_time1_page2<-surv_var1_page2[1]
      surv_time2_page2<-surv_var2_page2[1]

      long_data_page2<-defaultlongdata_page2()
      surv_data_page2<-defaultsurvdata_page2()
      time_point1_page2<-input$time_points1_page2
      time_point2_page2<-input$time_points2_page2

      newdata_page2<-long_data_page2[long_data_page2[[input$idvar_page2]]==rv$idnum_page2,]
      newdata_page2<-newdata_page2[newdata_page2[[input$timevar_page2]]<time_point1_page2,]
      newdata_page2[[surv_status1_page2]]<-0
      newdata_page2[[surv_time1_page2]]<-time_point1_page2
      newdata_page2[[surv_time2_page2]]<-time_point2_page2
      newdata_page2[[surv_status2_page2]]<-0

      newdata_page2[[input$timevar_page2]]<-as.numeric(as.character(newdata_page2[[input$timevar_page2]]))
      newdata_page2[[surv_time1_page2]]<-as.numeric(as.character(newdata_page2[[surv_time1_page2]]))
      newdata_page2[[surv_time2_page2]]<-as.numeric(as.character(newdata_page2[[surv_time2_page2]]))


      #rv$idnum_page2
      #summary(newdata_page2)
      #plot(rv$model_page2,newdata_page2)
      #############################################################################

      x<-rv$model_page2
      y<-newdata_page2
      result<-x
      ID<-x$IDvar
      y<-as.data.frame(y)
      newdata<-y
      t0<-max(newdata[result$timeVar])
      timeVar<-x$timeVar
      idnumber<-as.numeric(unique(newdata[,ID]))
      if(result$BIGdata==F){
        long1_res<-x$model1$model_info$var_names$respVars[[1]]
        long2_res<-x$model2$model_info$var_names$respVars[[1]]
        surv1_var<-x$model1$model_info$var_names$Time_var
        surv2_var<-x$model2$model_info$var_names$Time_var
        surv1_time<-unique(newdata[,surv1_var])
        surv2_time<-unique(newdata[,surv2_var])
        survtime<-c(surv1_time,surv2_time)
        if(isTRUE(surv1_time<surv2_time)){
          surv1_time<-survtime[1]
          surv2_time<-survtime[2]
        }else{
          surv1_time<-survtime[2]
          surv2_time<-survtime[1]
        }
        pred_long1<-predict(result$model1,newdata=newdata,process='longitudinal')
        if(isTRUE(survtime[1]<survtime[2])){
          pred_surv1<-predict(result$model1,newdata=newdata,process='event',times=seq(surv1_time,surv2_time,length.out=20))
        }else{
          pred_surv1<-predict(result$model2,newdata=newdata,process='event',times=seq(surv1_time,surv2_time,length.out=20))
        }
        pred_long2<-predict(result$model2,newdata=newdata,process='longitudinal')
        if(isTRUE(survtime[1]<survtime[2])){
          pred_surv2<-predict(result$model2,newdata=newdata,process='event',times=seq(surv2_time,2*surv2_time,length.out=20))
        }else{
          pred_surv2<-predict(result$model1,newdata=newdata,process='event',times=seq(surv2_time,2*surv2_time,length.out=20))
        }
        pred_list<-list(long1<-data.frame(Prediction=as.vector(unlist(pred_long1$preds)),
                                          UppL=as.vector(unlist(pred_long1$upp)),
                                          LwrL=as.vector(unlist(pred_long1$low)),
                                          Time=newdata[,timeVar],
                                          yvalue=newdata[,long1_res]),
                        long2<-data.frame(Prediction=as.vector(unlist(pred_long2$preds)),
                                          UppL=as.vector(unlist(pred_long2$upp)),
                                          LwrL=as.vector(unlist(pred_long2$low)),
                                          Time=newdata[,timeVar],
                                          yvalue=newdata[,long2_res]),

                        surv1<-data.frame(Prediction=unlist(pred_surv1$pred),UL=unlist(pred_surv1$upp),LL=unlist(pred_surv1$low),Time=unlist(pred_surv1$times)),
                        surv2<-data.frame(Prediction=unlist(pred_surv2$pred),UL=unlist(pred_surv2$upp),LL=unlist(pred_surv2$low),Time=unlist(pred_surv2$times))
        )
        pred_list[[3]]$Prediction<-1-pred_list[[3]]$Prediction
        pred_list[[3]]$UL<-1-pred_list[[3]]$UL
        pred_list[[3]]$LL<-1-pred_list[[3]]$LL
        pred_list[[4]]$Prediction<-1-pred_list[[4]]$Prediction
        pred_list[[4]]$UL<-1-pred_list[[4]]$UL
        pred_list[[4]]$LL<-1-pred_list[[4]]$LL
      }else{
        long1_res<-result$model1$pseudoMod$model_info$var_names$respVars[[1]]
        long2_res<-result$model2$pseudoMod$model_info$var_names$respVars[[1]]
        surv1_var<-result$model1$pseudoMod$model_info$var_names$Time_var[[1]]
        surv2_var<-result$model2$pseudoMod$model_info$var_names$Time_var[[1]]
        surv1_time<-as.numeric(unique(newdata[,surv1_var]))
        surv2_time<-as.numeric(unique(newdata[,surv2_var]))
        survtime<-c(surv1_time,surv2_time)
        if(isTRUE(surv1_time<surv2_time)){
          surv1_time<-survtime[1]
          surv2_time<-survtime[2]
        }else{
          surv1_time<-survtime[2]
          surv2_time<-survtime[1]
        }

        pred_long1<-predJMbayes(model=result$model1,ids=idnumber,newdata=newdata,process='longitudinal')
        if(isTRUE(survtime[1]<survtime[2])){
          pred_surv1<-predJMbayes(model=result$model1,newdata=newdata,ids=idnumber,process='event',times=seq(surv1_time,surv2_time,length.out=20))
        }else{
          pred_surv1<-predJMbayes(model=result$model2,newdata=newdata,ids=idnumber,process='event',times=seq(surv1_time,surv2_time,length.out=20))
        }
        pred_long2<-predJMbayes(result$model2,newdata=newdata,ids=idnumber,process='longitudinal')

        if(isTRUE(survtime[1]<survtime[2])){
          pred_surv2<-predJMbayes(result$model2,newdata=newdata,ids=idnumber,process='event',times=seq(surv2_time,2*surv2_time,length.out=20))
        }else{
          pred_surv2<-predJMbayes(result$model1,newdata=newdata,ids=idnumber,process='event',times=seq(surv2_time,2*surv2_time,length.out=20))
        }
        pred_list<-list(long1<-data.frame(Prediction=as.vector(unlist(pred_long1$P1[,long1_res])),
                                          UppL=as.vector(unlist(pred_long1$P1[,paste0('upp_',long1_res)])),
                                          LwrL=as.vector(unlist(pred_long1$P1[,paste0('low_',long1_res)])),
                                          Time=as.numeric(unlist(newdata[,timeVar])),
                                          yvalue=as.numeric(unlist(newdata[,long1_res]))),
                        long2<-data.frame(Prediction=as.vector(unlist(pred_long2$P1[,long2_res])),
                                          UppL=as.vector(unlist(pred_long2$P1[,paste0('upp_',long2_res)])),
                                          LwrL=as.vector(unlist(pred_long2$P1[,paste0('low_',long2_res)])),
                                          Time=as.numeric(unlist(newdata[,timeVar])),
                                          yvalue=as.numeric(unlist(newdata[,long2_res]))),

                        surv1<-data.frame(Prediction=unlist(pred_surv1$P1[,"pred_CIF"]),UL=unlist(pred_surv1$P1[,'upp_CIF']),LL=unlist(pred_surv1$P1[,'low_CIF']),Time=unlist(pred_surv1$P1[,timeVar])),
                        surv2<-data.frame(Prediction=unlist(pred_surv2$P1[,"pred_CIF"]),UL=unlist(pred_surv2$P1[,'upp_CIF']),LL=unlist(pred_surv2$P1[,'low_CIF']),Time=unlist(pred_surv2$P1[,timeVar]))
        )
        pred_list[[3]]$Prediction<-1-pred_list[[3]]$Prediction
        pred_list[[3]]$UL<-1-pred_list[[3]]$UL
        pred_list[[3]]$LL<-1-pred_list[[3]]$LL
        pred_list[[4]]$Prediction<-1-pred_list[[4]]$Prediction
        pred_list[[4]]$UL<-1-pred_list[[4]]$UL
        pred_list[[4]]$LL<-1-pred_list[[4]]$LL
      }

      K<-2
      m<-cbind(1:K,rep(K+1,K),rep(K+2,K))
      xticks<-pretty(c(pred_list[[1]]$Time,pred_list[[2]]$Time))
      widths<-c(0.3,0.35,0.35)
      layout(m,widths=widths)
      par(mar=c(0,4.5,0,0),oma=c(4,0,3,0),cex.axis=1.1,font.axis=2,font.lab=2,font.main=2)
      plot(x=pred_list[[1]]$Time,y=pred_list[[1]]$yvalue,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=pred_list[[1]]$Time,y=pred_list[[1]]$yvalue,pch=8,col='red')
      box(lwd=1.3)
      mtext(long1_res,line=2.5,side=2,font=2)
      par(mar = c(0, 4.5, 0, 0))
      plot(x=pred_list[[2]]$Time,y=pred_list[[2]]$yvalue,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=pred_list[[2]]$Time,y=pred_list[[2]]$yvalue,pch=8,col='red')
      axis(1, at = xticks)
      box(lwd=1.3)
      mtext(long2_res,line=2.5,side=2,font=2)
      xticks<-pretty(c(pred_list[[3]]$Time))
      par(mar=c(0,0,0,0))
      plot(x=pred_list[[3]]$Time,y=pred_list[[3]]$Prediction,col='black',type='l',las=1,yaxt='n',xaxs='i',xaxt='n',ylab='',ylim=c(0,1))
      polygon(c(pred_list[[3]]$Time,rev(pred_list[[3]]$Time)),c(pred_list[[3]]$UL,rev(pred_list[[3]]$LL)),col=rgb(0,0,0.6,0.4),border=NA)
      lines(x=pred_list[[3]]$Time,y=pred_list[[3]]$Prediction,col='blue',lwd=2)
      text(x=median(pred_list[[3]]$Time),y=0.99,labels =ifelse(isTRUE(survtime[1]<survtime[2]),'Event 1','Event 2'), pos = 3, col = "black",cex=1.6,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      xticks<-pretty(c(pred_list[[4]]$Time))
      par(mar=c(0,0,0,4.5))
      plot(x=pred_list[[4]]$Time,y=pred_list[[4]]$Prediction,col='black',type='l',las=1,yaxt='n',xaxs='i',xaxt='n',ylab='',ylim=c(0,1))
      polygon(c(pred_list[[4]]$Time,rev(pred_list[[4]]$Time)),c(pred_list[[4]]$UL,rev(pred_list[[4]]$LL)),col=rgb(0.6,0,0.6,0.4),border = NA)
      lines(x=pred_list[[4]]$Time,pred_list[[4]]$Prediction,col='red',lwd=2)
      text(x=median(pred_list[[4]]$Time),y=0.99,labels = ifelse(isTRUE(survtime[1]<survtime[2]),'Event 2','Event 1'), pos = 3, col = "black",cex=1.6,font=2)
      axis(1, at = xticks)
      axis(4,las=1)
      mtext('Plot for Bidirectional survival data', 3,
            line = 1, outer = TRUE, font = 2, cex = 1.3)
      mtext("Time", 1,
            line = 2.5, outer = TRUE,font=2)
      mtext("Survival Prediction", 4,
            line = 2.5,font=2)
      box(lwd=1.3)
      ##########################################################################
      ###########################################################################


    })
  })
  
  
  # Step 4: Delete the file when the session ends
  session$onSessionEnded(function() {
    if (file.exists(temp_file)) {
      file.remove(temp_file)
    }
  })

}
, 
options = list(height=1000,width="100%")
)

```


jmcsB
=====================================  
  
  Column {data-width=1000}
-------------------------------------

```{r}

shinyApp(
ui_page3<-fluidPage(
  tags$style(HTML("
    /* Change entire page background */
    body { background-color: #f0f8ff; } /* Light blue */

    /* Style for the main title */
    .main-title { color: darkblue; font-size: 28px; font-weight: bold; text-align: center; }

    /* Styling for different text elements */
    .summary-text { color: blue; }
    .plot-title { color: darkred; font-size: 20px; font-weight: bold; }

    /* Change color of sidebar panel text */
    .sidebar-label { color: blue; font-weight: bold; }

    /* Change color of all sidebar input labels */
    .control-label, .shiny-options-group label { color: darkred; font-size: 16px; font-weight: bold; }

    /* Style for select input dropdown */
    .sidebar-input select { color: darkgreen; font-weight: bold; }

    /* Change color of action button text */
    #submit_page3 { background-color: white; color: red; border: 2px solid red; font-weight: bold; }

    /* OPTIONAL: Add hover effect to the submit button */
    #submit_page3:hover { background-color: red; color: white; }

    /* Customize sidebar background */
    .well { background-color: #e6f2ff; border-radius: 10px; } /* Light blue */

    /* Customize main panel background */
    .main-panel { background-color: #ffffff; padding: 20px; border-radius: 10px; }

      .custom-text-output {
      color: rgb(0, 70, 0);  /* Change text color */
      font-size: 15px;   /* Adjust font size */
      font-family: 'Times New Roman', Times, serif;/* Use monospace font */
      background-color: #f4f4f4; /* Light gray background */
      padding: 10px; /* Add padding */
      border-radius: 5px; /* Rounded corners */
      }
    /* Change text color inside text input fields */
    .form-control {
      color: darkred !important; /* Change text color */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Change text color inside all selectInput dropdowns */
    .selectize-input {
      color: darkred !important;  /* Change dropdown text color */
      font-weight: bold !important;
      font-size: 16px !important;
      /*background-color: lightgray !important;  Change background */
      /*border: 2px solid red !important;   Change border color */
    }

    /* Change text color inside the dropdown list */
    .selectize-dropdown-content {
      color: darkred !important; /* Change dropdown option text */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Hover effect for dropdown options */
    .selectize-dropdown-content .option:hover {
      background-color: yellow !important;  /* Change hover background */
      color: black !important;  /* Change text color on hover */
    }

    /* Custom styling for the DT table */
    .styled-table .dataTable {
        border-collapse: collapse;
        width: 40%;
        font-size: 6px;
        border: 1px solid #ddd;
    }

    /* Header styling */
    .styled-table .dataTable thead {
        background-color: darkblue;
        color: white;
    }

    /* Row hover effect */
    .styled-table .dataTable tbody tr:hover {
        background-color: #e6f2ff; /* Light blue */
    }

    /* Border for table */
    .styled-table .dataTable tbody td {
        border: 1px solid #ddd;
        padding: 5px;
    }

    .gif-container {
  display: flex;
  justify-content: flex-end; /* Center horizontally */
  align-items: center; /* Center vertically (if needed) */
  margin-top: 20px;
  padding: 10px; /* Add some space inside */
  border: 3px solid #3498db; /* Blue border */
  border-radius: 10px; /* Rounded corners */
  background-color: #f9f9f9; /* Light background */
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1); /* Soft shadow */
  width: 420px; /* Box width slightly larger than GIF */
  height: 410px; /* Box height */
}

.gif-container img {
  width: 400px;  /* Adjust size */
  height: auto;
}
")),

  titlePanel(tags$h1("Joint Model for longitudinal and multiple time-to-events data using jmcsB() function",class="main-title")),
  sidebarLayout(
    sidebarPanel(
      radioButtons("data_option_page3", span("Select data source:",class="sidebar-label"),
                   c("Upload my own dataset" = "upload",
                     "Use default dataset" = "default")),
      conditionalPanel(
        condition = "input.data_option_page3== 'default' & input.Bigdata_page3=='No'",
        sliderInput("pid_page3", span("Select ID No. :",class="sidebar-label"), min = min(simulated_sdata$id), max = 100, value = 50)
      ),

      conditionalPanel(
        condition = "input.data_option_page3== 'default' & input.Bigdata_page3=='Yes'",
        sliderInput("pidBIG_page3", span("Select ID No. :",class="sidebar-label"), min = min(new_surv2$id), max = 600, value = 10)
      ),


      conditionalPanel(
        condition = "input.data_option_page3 == 'upload'",
        fileInput("lfile_page3", span("Upload Longitudinal Data (CSV format)",class="sidebar-label")),
        fileInput("sfile_page3", span("Upload Survival Data (CSV format)",class="sidebar-label")),
        uiOutput("pid_slider_upload_page3")
      ),

      selectInput("Bigdata_page3", span("Is the sample size geater than 500?",class="sidebar-label"), choices =c("Yes","No")),
      selectInput("idvar_page3", span("ID variable",class="sidebar-label"), choices =NULL),
      selectInput("timevar_page3", span("Visit time",class="sidebar-label"), choices = NULL),


      textInput("longmodel1_page3", span("Longitudinal data model (For event 1)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel1_page3", span("Longitudinal data model random effect part (For event 1)",class="sidebar-label"), value = "~visit|id"),

      textInput("longmodel2_page3",span("Longitudinal data model (For event 2)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel2_page3", span("Longitudinal data model random effect part (For event 2)",class="sidebar-label"), value = "~visit|id"),
      textInput("survmodel1_page3",span("Survival data model (For event 1)",class="sidebar-label"), value = "Surv(time,status)~x1+visit"),
      textInput("survmodel2_page3", span("Survival data model (For event 2)",class="sidebar-label"), value = "Surv(time_2,status_2)~x1+visit"),
      textInput("time_points1_page3",span("Time points for plot (event 1):",class="sidebar-label"),value=4),
      textInput("time_points2_page3",span("Time points for plot (event 2):",class="sidebar-label"),value=9),
      #selectInput("Bigdata_page3", "Is it BIG data", choices =c("Yes","No")),
      numericInput("samplesize_page3", span("Loop size",class="sidebar-label"), value = 200),
      actionButton("submit_page3",span("Submit",class="submit_page3"))
    ),

    mainPanel(
      #tags$img(src = "jmbdirect_animation.gif", height = "400px", width = "400px"),
      # div(
      #   class = "gif-container",
      #   tags$img(src = "jmbdirect_animation.gif", width = "500px", height = "500px")
      # ),
      #imageOutput("image_output_page3"),
      #imageOutput("image_output_page3"),
      p('jmcsB(): a function for joint model in small data as well as BIG DATA using FastJM, jmBIG package. For more information about the arguments of the function please look ',a("here.",href = "https://cran.r-project.org/web/packages/JMbdirect/index.html")),
      div(
           style = "margin-left: 90px; text-align: center;",
          h6(
            "Fig: The figure shows the longitudinal and survival plots", br(),
            "for Subject ID: 1 to 100",
            style = "color: darkred; font-weight: bold; font-style: italic;"
          ),
          imageOutput("image_output_page3"),
          
        ),

      h4(strong("An example R Code for the model:"),class="summary-text"),
      div(class = "custom-text-output",uiOutput("rCode_page3")),
      h4(strong("Model summary:"),class="summary-text"),
      div(verbatimTextOutput("summarymodel_page3"),class = "custom-text-output"),
      h4(strong("Selected ID information:"),class="summary-text"),
      div(textOutput("selected_var_page3"),class= "custom-text-output"),
      div(dataTableOutput('longID_page3'),class="custom-text-output"),
      h4(strong("Plot for the selected ID:"),class="summary-text"),
      div(textOutput("selectedID_page3"),class="custom-text-output"),
      shinycssloaders::withSpinner(plotOutput('summaryplot_page3'))

    )
  )
),

server_page3<-function(input, output, session){

  temp_file <- tempfile(fileext = ".gif")
  
  # Step 2: Download the file from Google Drive
  gif_url <- "https://drive.google.com/uc?id=1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3"
  
  download.file(gif_url, temp_file, mode = "wb")  # Save as binary file
  output$image_output_page3 <- renderImage({
    list(
      src = temp_file,
      contentType = "image/gif",
      width = 410,
      height = 350
    )
  }, deleteFile = FALSE)  # Don't delete immediately, we'll do it manually

  
  
  output$rCode_page3 <- renderUI({
HTML("model_jmcs<-jmcsB(dtlong=....,dtsurv=....,<br>
longm=list(serBilir~drug*year,serBilir~drug*year),<br>
survm=list(Surv(years,status2)~drug,Surv(time_2,status_2)~drug+age),<br>
rd=list(~1|id,~1|id),id='id',timeVar='year')<br><br>
<b>Here is the list of entries in side bar panel according to this example(default small data):</b><br>
ID variable: id<br>
Visit time: year<br>
Longitudinal data model (For event 1): serBilir~drug*year<br>
Longitudinal data model random effect part (For event 1): ~1|id<br>
Longitudinal data model (For event 2): serBilir~drug*year<br>
Longitudinal data model random effect part (For event 2): ~1|id<br>
Survival data model (For event 1): Surv(years,status2)~drug<br>
Survival data model (For event 2): Surv(time_2,status_2)~drug+age<br>
Time points for plot (event 1): 6<br>
Time points for plot (event 2): 10<br>
Is it BIG data: No<br>
Loop size: 200(you may use other also)")
  })

  defaultsurvdata_page3 <- reactive({
    if (input$data_option_page3 == 'upload') {
      req(input$sfile_page3)
      defaultsurvdata_page3 <- read.csv(input$sfile_page3$datapath)
    } else {
      if(input$Bigdata_page3=="Yes"){
        defaultsurvdata_page3 <- new_surv2[new_surv2$id<=600,]
      }else{
        defaultsurvdata_page3 <- simulated_sdata
      }
    }
    return(defaultsurvdata_page3)
  })


  observeEvent(defaultsurvdata_page3(), {
    updateSelectInput(session, "idvar_page3", choices = names(defaultsurvdata_page3()))
    updateSelectInput(session, "timevar_page3", choices = names(defaultsurvdata_page3()))
    updateSelectInput(session, "event_page3", choices = names(defaultsurvdata_page3()))
    updateSelectInput(session, "obs_time_page3", choices = names(defaultsurvdata_page3()))
  })



  defaultlongdata_page3 <- reactive({
    if (input$data_option_page3 == 'upload') {
      req(input$lfile_page3)
      defaultlongdata_page3 <- read.csv(input$lfile_page3$datapath)
    } else {

      if(input$Bigdata_page3=="Yes"){
        defaultlongdata_page3 <- new_long2[new_long2$id<=600,]
      }else{
        defaultlongdata_page3 <- simulated_ldata
      }
    }
    return(defaultlongdata_page3)
  })


  output$pid_slider_upload_page3 <- renderUI({
    req(input$idvar_page3)
    tagList(
      selectInput("pid_page33", "Patient ID", choices=defaultsurvdata_page3()[[input$idvar_page3]],selectize = FALSE,size=5)
    )
  })

  output$selected_var_page3 <- reactive({

    if (input$data_option_page3 == "default") {
      req(input$Bigdata_page3)
      if(input$Bigdata_page3=="Yes"){
        req(input$pidBIG_page3)
        paste("You have selected patient ID", input$pidBIG_page3)
      }else{
        paste("You have selected patient ID", input$pid_page3)
      }
    } else {
      req(input$pid_page33)
      paste("Uploaded data selected with patient ID",input$pid_page33)
    }
  })

  output$selectedID_page3 <- reactive({

    if (input$data_option_page3 == "default") {
      req(input$pid_page3)
      req(input$Bigdata_page3)
      if(input$Bigdata_page3=="No"){
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmcsB() for the selected patient ID: ',input$pid_page3)
      }else{
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmcsB() for the selected patient ID: ',input$pidBIG_page3)
      }    } else {
      req(input$pid_page33)
      paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmcsB() for the selected patient ID: ',input$pid_page33)
    }
  })


  rv<-reactiveValues(model_page3=NULL,idnum_page3=NULL)

  longID_page3 <- reactive({

    if (input$data_option_page3 == "default") {
      req(input$pid_page3)
      req(input$timevar_page3)
      req(input$idvar_page3)
      req(input$Bigdata_page3)
      req(defaultlongdata_page3())
      req(defaultsurvdata_page3())

      surv_var1_page3<-all.vars(as.formula(input$survmodel1_page3))
      surv_var2_page3<-all.vars(as.formula(input$survmodel2_page3))
      surv_status1_page3<-surv_var1_page3[2]
      surv_status2_page3<-surv_var2_page3[2]
      surv_time1_page3<-surv_var1_page3[1]
      surv_time2_page3<-surv_var2_page3[1]

      long_data_page3<-defaultlongdata_page3()
      surv_data_page3<-defaultsurvdata_page3()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page3<-if(input$Bigdata_page3=='No'){input$pid_page3}else{input$pidBIG_page3}
      newdata_page3<-long_data_page3[long_data_page3[[input$idvar_page3]]==rv$idnum_page3,]
      newdata_page3

    } else {
      req(input$timevar_page3)
      req(input$idvar_page3)
      req(defaultlongdata_page3())
      req(defaultsurvdata_page3())
      req(input$pid_page33)
      #paste('Survival and longitudinal information for the selected patient ID: ',input$pid_page22)
      surv_var1_page3<-all.vars(as.formula(input$survmodel1_page3))
      surv_var2_page3<-all.vars(as.formula(input$survmodel2_page3))
      surv_status1_page3<-surv_var1_page3[2]
      surv_status2_page3<-surv_var2_page3[2]
      surv_time1_page3<-surv_var1_page3[1]
      surv_time2_page3<-surv_var2_page3[1]

      long_data_page3<-defaultlongdata_page3()
      surv_data_page3<-defaultsurvdata_page3()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page3<-input$pid_page33
      newdata_page3<-long_data_page3[long_data_page3[[input$idvar_page3]]==input$pid_page33,]
      newdata_page3
          }
  })


  observeEvent(input$submit_page3, {
    output$longID_page3 <- DT::renderDT({
      data_page3 <- as.data.frame(longID_page3())

      # Round numeric columns to 1 decimal place
      numeric_cols <- sapply(data_page3, is.numeric)
      data_page3[numeric_cols] <- lapply(data_page3[numeric_cols], round, 1)

      DT::datatable(data_page3,
                    options = list(
                      pageLength = 5,
                      autoWidth = TRUE,
                      dom = 'Bfrtip',
                      buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),  # Export options
                      scrollX = TRUE,
                      scrollCollapse = TRUE,# Enable horizontal scrolling
                      scrollY = "400px",  # Enable vertical scrolling with fixed height
                      paging = TRUE  # Keep pagination enabled
                    ),
                    class = "cell-border stripe hover",
                    width = "100%",  # Adjust table width
                    height = "500px"  # Adjust table height
      ) %>%
        DT::formatStyle(
          columns = names(data_page3),
          color = "black",
          backgroundColor = "#f0f8ff",  # Light blue
          fontSize = '10px'  # Change font size
        )
    })
  })


  #rv<-reactiveValues(model_page3=NULL)

  observeEvent(input$submit_page3,{
    output$summarymodel_page3 <- renderPrint({
      req(input$longmodel1_page3)
      req(input$longmodel2_page3)
      req(input$rdmodel1_page3)
      req(input$rdmodel2_page3)
      req(input$survmodel1_page3)
      req(input$survmodel2_page3)
      req(input$timevar_page3)
      req(input$idvar_page3)
      req(input$Bigdata_page3)
      req(defaultlongdata_page3())
      req(defaultsurvdata_page3())

      longmodel1_page3<-as.formula(input$longmodel1_page3)
      rdmodel1_page3<-as.formula(input$rdmodel1_page3)
      longmodel2_page3<-as.formula(input$longmodel2_page3)
      rdmodel2_page3<-as.formula(input$rdmodel2_page3)
      survmodel1_page3<-as.formula(input$survmodel1_page3)
      survmodel2_page3<-as.formula(input$survmodel2_page3)
      BIGdata_t<-ifelse(input$Bigdata_page3=="Yes",TRUE,FALSE)
      long_data_page3<-defaultlongdata_page3()
      surv_data_page3<-defaultsurvdata_page3()

      fitmodel_page33 <-jmcsB(dtlong=long_data_page3,
                              dtsurv=surv_data_page3,
                              longm=list(longmodel1_page3,longmodel2_page3),
                              survm=list(survmodel1_page3, survmodel2_page3),
                              rd=list(rdmodel1_page3,rdmodel2_page3),
                              timeVar=input$timevar_page3,
                              samplesize =200,
                              BIGdata=BIGdata_t,
                              id=input$idvar_page3)

      # rv$model_page3<-fitmodel_page33
      #fitmodel_page33<-survmodel1_page3
      rv$model_page3<-fitmodel_page33
      fitmodel_page33

    })
  })

  observeEvent(input$submit_page3,{
    output$summaryplot_page3<- renderPlot({
      req(input$timevar_page3)
      req(input$idvar_page3)
      #req(input$pid_page3)
      #req(input$time_points_page2)
      req(defaultlongdata_page3())
      req(defaultsurvdata_page3())
      req(input$time_points1_page3)
      req(input$time_points2_page3)

      surv_var1_page3<-all.vars(as.formula(input$survmodel1_page3))
      surv_var2_page3<-all.vars(as.formula(input$survmodel2_page3))
      surv_status1_page3<-surv_var1_page3[2]
      surv_status2_page3<-surv_var2_page3[2]
      surv_time1_page3<-surv_var1_page3[1]
      surv_time2_page3<-surv_var2_page3[1]

      long_data_page3<-defaultlongdata_page3()
      surv_data_page3<-defaultsurvdata_page3()
      time_point1_page3<-input$time_points1_page3
      time_point2_page3<-input$time_points2_page3

      newdata_page3<-long_data_page3[long_data_page3[[input$idvar_page3]]==rv$idnum_page3,]
      newdata_page3<-newdata_page3[newdata_page3[[input$timevar_page3]]<time_point1_page3,]
      newdata_page3[[surv_status1_page3]]<-0
      newdata_page3[[surv_time1_page3]]<-time_point1_page3
      newdata_page3[[surv_time2_page3]]<-time_point2_page3
      newdata_page3[[surv_status2_page3]]<-0

      newdata_page3[[input$timevar_page3]]<-as.numeric(as.character(newdata_page3[[input$timevar_page3]]))
      newdata_page3[[surv_time1_page3]]<-as.numeric(as.character(newdata_page3[[surv_time1_page3]]))
      newdata_page3[[surv_time2_page3]]<-as.numeric(as.character(newdata_page3[[surv_time2_page3]]))

      #summary(newdata_page3)
      #plot(rv$model_page2,newdata_page2)
      #############################################################################
      x<-rv$model_page3
      y<-newdata_page3

      result<-x
      IDvar<-x$IDvar
      y<-as.data.frame(y)
      ynewdata<-as.data.frame(y)
      cnewdata<-as.data.frame(y[!(duplicated(y[IDvar])),])
      timeVar<-x$timeVar
      idNumber<-as.numeric(cnewdata[,IDvar])
      if(result$BIGdata==F){
        long1_var<-all.vars(x$model1$LongitudinalSubmodel)[1]
        long2_var<-all.vars(x$model2$LongitudinalSubmodel)[1]
        surv1_var<-all.vars(x$model1$SurvivalSubmodel)[1]
        surv2_var<-all.vars(x$model2$SurvivalSubmodel)[1]
        #future_time1<-seq(ynewdata[,timeVar][nrow(ynewdata)],3*ynewdata[,timeVar][nrow(ynewdata)],1)
        t_0<-ynewdata[,surv1_var][nrow(ynewdata)]
        t_1<-ynewdata[,surv2_var][nrow(ynewdata)]
        #use bootstrap sample for 95% Confidence Interval

        bootstrap_longitudinal_survival <- function(longitudinal_data, survival_data, n_bootstrap = 10,id,idNumber){
          bootstrap_samples <- vector("list", length = n_bootstrap)
          unique_ids <- as.numeric(unique(longitudinal_data[[id]]))
          for (i in 1:n_bootstrap) {
            # Sample IDs with replacement
            bootstrap_ids <- sample(unique_ids[unique_ids!=idNumber], replace = TRUE)
            n_bootstrap_ids<-seq(1,length(unique(survival_data[[id]])))
            bootstrap_longitudinal_sample <- data.frame()
            bootstrap_survival_sample <- data.frame()
            count<-0
            for (j in 1:(length(bootstrap_ids))) {
              id_longitudinal_data <- longitudinal_data[longitudinal_data[[id]] == bootstrap_ids[j], ]
              id_longitudinal_data[[id]]<-j
              id_survival_data <- survival_data[survival_data[[id]] == bootstrap_ids[[j]], ]
              id_survival_data[[id]]<-j
              bootstrap_longitudinal_sample <- rbind(bootstrap_longitudinal_sample, id_longitudinal_data)
              bootstrap_survival_sample <- rbind(bootstrap_survival_sample, id_survival_data)
            }
            newdatalong<-longitudinal_data[longitudinal_data[id]==idNumber,]
            newdatalong[id]<-length(unique(longitudinal_data[[id]]))
            bootstrap_longitudinal_sample<-rbind(bootstrap_longitudinal_sample,newdatalong)
            newdatasurv<-survival_data[survival_data[id]==idNumber,]
            newdatasurv[id]<-length(unique(longitudinal_data[[id]]))
            bootstrap_survival_sample<-rbind(bootstrap_survival_sample,newdatasurv)
            bootstrap_samples[[i]] <- list(longitudinal = bootstrap_longitudinal_sample, survival = bootstrap_survival_sample)
          }
          return(bootstrap_samples)
        }
        bootstrapped_data <- bootstrap_longitudinal_survival(x$model1$ydata,
                                                             x$model1$cdata,
                                                             n_bootstrap = 30,id=IDvar,
                                                             idNumber = idNumber)

        if(t_0<=t_1){
          future_time1<-seq(t_0,t_1,length.out=20)
          future_time2<-seq(t_1,2*t_1,length.out=20)
          pred_model1<-survfitjmcs(object=result$model1,seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time1,method='Laplace',obs.time=timeVar)
          pred_model2<-survfitjmcs(object=result$model2,seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time2,method='Laplace',obs.time=timeVar)

          model1_list<-list();model2_list<-list()
          pred_model1_list<-list();pred_model2_list<-list();CIdata_model1<-list();
          CIdata_model2<-list()
          for(i in 1:length(bootstrapped_data)){
            model1_list[[i]]<-jmcs(ydata=bootstrapped_data[[i]]$longitudinal,
                                   cdata=bootstrapped_data[[i]]$survival,
                                   long.formula=x$model1$LongitudinalSubmodel,
                                   surv.formula=x$model1$SurvivalSubmodel,
                                   random=x$model1$random)
            model2_list[[i]]<-jmcs(ydata=bootstrapped_data[[i]]$longitudinal,
                                   cdata=bootstrapped_data[[i]]$survival,
                                   long.formula=x$model2$LongitudinalSubmodel,
                                   surv.formula=x$model2$SurvivalSubmodel,
                                   random=x$model2$random)
            pred_model1_list[[i]]<-survfitjmcs(object=model1_list[[i]],seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time1,method='Laplace',obs.time=timeVar)
            pred_model2_list[[i]]<-survfitjmcs(object=model2_list[[i]],seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time2,method='Laplace',obs.time=timeVar)
            CIdata_model1[[i]]<-pred_model1_list[[i]]$Pred[[1]]$PredSurv
            CIdata_model2[[i]]<-pred_model2_list[[i]]$Pred[[1]]$PredSurv
          }

        }else{
          future_time1<-seq(t_1,t_0,length.out=20)
          future_time2<-seq(t_0,2*t_0,length.out=20)
          pred_model1<-survfitjmcs(object=result$model2,seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time1,method='Laplace',obs.time=timeVar)
          pred_model2<-survfitjmcs(object=result$model1,seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time2,method='Laplace',obs.time=timeVar)
          model1_list<-list();model2_list<-list()
          pred_model1_list<-list();pred_model2_list<-list();CIdata_model1<-list()
          CIdata_model2<-list()
          for(i in 1:length(bootstrapped_data)){
            model1_list[[i]]<-jmcs(ydata=bootstrapped_data[[i]]$longitudinal,
                                   cdata=bootstrapped_data[[i]]$survival,
                                   long.formula=x$model2$LongitudinalSubmodel,
                                   surv.formula=x$model2$SurvivalSubmodel,
                                   random=x$model2$random)
            model2_list[[i]]<-jmcs(ydata=bootstrapped_data[[i]]$longitudinal,
                                   cdata=bootstrapped_data[[i]]$survival,
                                   long.formula=x$model1$LongitudinalSubmodel,
                                   surv.formula=x$model1$SurvivalSubmodel,
                                   random=x$model1$random)
            pred_model1_list[[i]]<-survfitjmcs(object=model2_list[[i]],seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time1,method='Laplace',obs.time=timeVar)
            pred_model2_list[[i]]<-survfitjmcs(object=model1_list[[i]],seed=100,ynewdata=ynewdata,cnewdata=cnewdata,u=future_time2,method='Laplace',obs.time=timeVar)
            CIdata_model1[[i]]<-pred_model1_list[[i]]$Pred[[1]]$PredSurv
            CIdata_model2[[i]]<-pred_model2_list[[i]]$Pred[[1]]$PredSurv

          }
        }
        CIdata_model1<-Reduce('cbind',CIdata_model1)
        CIdata_model2<-Reduce('cbind',CIdata_model2)


        y_obs <- data.frame(year = pred_model1$y.obs[[1]][,timeVar],
                            Marker1 = pred_model1$y.obs[[1]][,long1_var])

        pred_surv <- data.frame(times = pred_model1$Pred[[1]]$times,
                                PredSurv = apply(CIdata_model1,1,function(x){quantile(x,0.5)}),
                                LL=apply(CIdata_model1,1,function(x){quantile(x,0.025)}),
                                UL=apply(CIdata_model1,1,function(x){quantile(x,0.975)})
        )

        y_obs_2<-data.frame(year=pred_model2$y.obs[[1]][,timeVar],
                            Marker2=pred_model2$y.obs[[1]][,long2_var])

        pred_surv2<-data.frame(times = pred_model2$Pred[[1]]$times,
                               PredSurv =apply(CIdata_model2,1,function(x){quantile(x,0.5)}),
                               LL=apply(CIdata_model2,1,function(x){quantile(x,0.025)}),
                               UL=apply(CIdata_model2,1,function(x){quantile(x,0.975)})
        )
        abline_point1<-min(pred_surv$times)
        abline_point2<-max(pred_surv$times)
      }else{

        long1_var<-all.vars(result$model1$pseudoMod$LongitudinalSubmodel)[1]
        long2_var<-all.vars(result$model2$pseudoMod$LongitudinalSubmodel)[1]
        surv1_var<-all.vars(result$model1$pseudoMod$SurvivalSubmodel)[1]
        surv2_var<-all.vars(result$model2$pseudoMod$SurvivalSubmodel)[1]

        future_time1<-seq(ynewdata[,surv1_var][nrow(ynewdata)],ynewdata[,surv2_var][nrow(ynewdata)],length.out=20)
        future_time2<-seq(ynewdata[,surv2_var][nrow(ynewdata)],2*ynewdata[,surv2_var][nrow(ynewdata)],length.out=20)

        t_0<-ynewdata[,surv1_var][nrow(ynewdata)]
        t_1<-ynewdata[,surv2_var][nrow(ynewdata)]

        if(t_0<=t_1){
          future_time1<-seq(t_0,t_1,length.out=20)
          future_time2<-seq(t_1,2*t_1,length.out=20)
          pred_model1<-survfitJMCS(model=result$model1,ids=idNumber,method='Laplace',u=future_time1,obs.time = timeVar)
          pred_model2<-survfitJMCS(model=result$model2,ids=idNumber,method='Laplace',u=future_time2,obs.time=timeVar)
          bootci_model1<-bootciJMCS(pred_model1,future_time = future_time1)
          bootci_model2<-bootciJMCS(pred_model2,future_time = future_time2)
        }else{
          future_time1<-seq(t_1,t_0,length.out=20)
          future_time2<-seq(t_0,2*t_0,length.out=20)
          pred_model1<-survfitJMCS(model=result$model2,ids=ID,method='Laplace',u=future_time1,obs.time = timeVar)
          pred_model2<-survfitJMCS(model=result$model1,ids=ID,method='Laplace',u=future_time2,obs.time=timeVar)
          bootci_model1<-bootciJMCS(pred_model1,future_time = future_time1)
          bootci_model2<-bootciJMCS(pred_model2,future_time = future_time2)


        }
        y_obs <- data.frame(year = pred_model1$P1$y.obs[[1]][,timeVar],Marker1 = pred_model1$P1$y.obs[[1]][,long1_var])
        pred_surv <- data.frame(times = bootci_model1$bootCI$Times,
                                PredSurv =bootci_model1$bootCI$Med ,
                                LL=bootci_model1$bootCI$LL,
                                UL=bootci_model1$bootCI$UL)
        y_obs_2<-data.frame(year=pred_model2$P1$y.obs[[1]][,timeVar],
                            Marker2=pred_model2$P1$y.obs[[1]][,long2_var])

        pred_surv2<-data.frame(times = bootci_model2$bootCI$Times,
                               PredSurv =bootci_model2$bootCI$Med,
                               LL=bootci_model2$bootCI$LL,
                               UL=bootci_model2$bootCI$UL)

      }
      pred_surv$PredSurv<-ifelse(pred_surv$PredSurv>=1,1,pred_surv$PredSurv)
      pred_surv$LL<-ifelse(pred_surv$LL>=1,1,pred_surv$LL)
      pred_surv$UL<-ifelse(pred_surv$UL>=1,1,pred_surv$UL)
      pred_surv2$PredSurv<-ifelse(pred_surv2$PredSurv>=1,1,pred_surv2$PredSurv)
      pred_surv2$LL<-ifelse(pred_surv2$LL>=1,1,pred_surv2$LL)
      pred_surv2$UL<-ifelse(pred_surv2$UL>=1,1,pred_surv2$UL)
      K<-2
      m<-cbind(1:K,rep(K+1,K),rep(K+2,K))
      xticks<-pretty(c(y_obs$year,y_obs_2$year))
      widths<-c(0.3,0.35,0.35)
      layout(m,widths=widths)
      par(mar=c(0,4.5,0,0),oma=c(4,0,3,0),cex.axis=1.1,font.axis=2,font.lab=2,font.main=2)
      plot(x=y_obs$year,y=y_obs$Marker1,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=y_obs$year,y=y_obs$Marker1,pch=8,col='red')
      mtext(long1_var,line=2.5,side=2,font=2)
      box(lwd=1.3)
      par(mar = c(0, 4.5, 0, 0))
      plot(x=y_obs_2$year,y=y_obs_2$Marker2,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=y_obs_2$year,y=y_obs_2$Marker2,pch=8,col='red')
      mtext(long2_var,line=2.5,side=2,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      par(mar=c(0,0,0,0))
      xticks<-pretty(c(pred_surv$times))
      plot(x=pred_surv$times,y=pred_surv$PredSurv,col='black',type='l',las=1,yaxt='n',xaxs='i',xaxt='n',ylab='',ylim=c(0,1))
      polygon(c(pred_surv$times,rev(pred_surv$times)),c(pred_surv$UL,rev(pred_surv$LL)),col=rgb(0,0,0.6,0.4),border=NA)
      lines(x=pred_surv$times,y=pred_surv$PredSurv,col='blue',lwd=2)
      text(x=median(pred_surv$times),y=0.99,labels = ifelse(t_0<=t_1,"Event 1","Event 2"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      par(mar=c(0,0,0,4.5))
      xticks<-pretty(c(pred_surv2$times))
      plot(x=pred_surv2$times,y=pred_surv2$PredSurv,col='black',type='l',las=1,yaxt='n',xaxt='n',xaxs='i',ylab='',ylim=c(0,1))
      polygon(c(pred_surv2$times,rev(pred_surv2$times)),c(pred_surv2$UL,rev(pred_surv2$LL)),col=rgb(0.6,0,0.6,0.4),border = NA)
      lines(x=pred_surv2$times,y=pred_surv2$PredSurv,col='red',lwd=2)
      text(x=median(pred_surv2$times),y=0.99,labels = ifelse(t_0<=t_1,"Event 2","Event 1"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      axis(4,las=1)
      mtext('Plot for Bidirectional survival data', 3,
            line = 1, outer = TRUE, font = 2, cex = 1.3)
      mtext("Time", 1,
            line = 2.5, outer = TRUE,font=2)
      mtext("Survival Prediction", 4,
            line = 2.5,font=2)
      box(lwd=1.3)
      ##########################################################################
      ###########################################################################
    })
  })
  
  # Step 4: Delete the file when the session ends
  session$onSessionEnded(function() {
    if (file.exists(temp_file)) {
      file.remove(temp_file)
    }
  })
  
}

, 
options = list(height=1000,width="100%")
)

```


jmrmlB
=====================================  
  
Column {data-width=1000}
-------------------------------------

```{r}

shinyApp(
ui_page4<-fluidPage(
  tags$style(HTML("
    /* Change entire page background */
    body { background-color: #f0f8ff; } /* Light blue */

    /* Style for the main title */
    .main-title { color: darkblue; font-size: 28px; font-weight: bold; text-align: center; }

    /* Styling for different text elements */
    .summary-text { color: blue; }
    .plot-title { color: darkred; font-size: 20px; font-weight: bold; }

    /* Change color of sidebar panel text */
    .sidebar-label { color: blue; font-weight: bold; }

    /* Change color of all sidebar input labels */
    .control-label, .shiny-options-group label { color: darkred; font-size: 16px; font-weight: bold; }

    /* Style for select input dropdown */
    .sidebar-input select { color: darkgreen; font-weight: bold; }

    /* Change color of action button text */
    #submit_page4 { background-color: white; color: red; border: 2px solid red; font-weight: bold; }

    /* OPTIONAL: Add hover effect to the submit button */
    #submit_page4:hover { background-color: red; color: white; }

    /* Customize sidebar background */
    .well { background-color: #e6f2ff; border-radius: 10px; } /* Light blue */

    /* Customize main panel background */
    .main-panel { background-color: #ffffff; padding: 20px; border-radius: 10px; }

      .custom-text-output {
      color: rgb(0, 70, 0);  /* Change text color */
      font-size: 15px;   /* Adjust font size */
      font-family: 'Times New Roman', Times, serif;/* Use monospace font */
      background-color: #f4f4f4; /* Light gray background */
      padding: 10px; /* Add padding */
      border-radius: 5px; /* Rounded corners */
      }
    /* Change text color inside text input fields */
    .form-control {
      color: darkred !important; /* Change text color */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Change text color inside all selectInput dropdowns */
    .selectize-input {
      color: darkred !important;  /* Change dropdown text color */
      font-weight: bold !important;
      font-size: 16px !important;
      /*background-color: lightgray !important;  Change background */
      /*border: 2px solid red !important;   Change border color */
    }

    /* Change text color inside the dropdown list */
    .selectize-dropdown-content {
      color: darkred !important; /* Change dropdown option text */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Hover effect for dropdown options */
    .selectize-dropdown-content .option:hover {
      background-color: yellow !important;  /* Change hover background */
      color: black !important;  /* Change text color on hover */
    }

    /* Custom styling for the DT table */
    .styled-table .dataTable {
        border-collapse: collapse;
        width: 40%;
        font-size: 6px;
        border: 1px solid #ddd;
    }

    /* Header styling */
    .styled-table .dataTable thead {
        background-color: darkblue;
        color: white;
    }

    /* Row hover effect */
    .styled-table .dataTable tbody tr:hover {
        background-color: #e6f2ff; /* Light blue */
    }

    /* Border for table */
    .styled-table .dataTable tbody td {
        border: 1px solid #ddd;
        padding: 5px;
    }

    .gif-container {
  display: flex;
  justify-content: flex-end; /* Center horizontally */
  align-items: center; /* Center vertically (if needed) */
  margin-top: 20px;
  padding: 10px; /* Add some space inside */
  border: 3px solid #3498db; /* Blue border */
  border-radius: 10px; /* Rounded corners */
  background-color: #f9f9f9; /* Light background */
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1); /* Soft shadow */
  width: 420px; /* Box width slightly larger than GIF */
  height: 410px; /* Box height */
}

.gif-container img {
  width: 400px;  /* Adjust size */
  height: auto;
}
")),
  titlePanel(tags$h1("Joint Model for longitudinal and multiple time-to-events data using jmrmlB() function",class="main-title")),
  sidebarLayout(
    sidebarPanel(
      radioButtons("data_option_page4", span("Select data source:",class="sidebar-label"),
                   c("Upload my own dataset" = "upload",
                     "Use default dataset" = "default")),
      conditionalPanel(
        condition = "input.data_option_page4== 'default' & input.Bigdata_page4=='No'",
        sliderInput("pid_page4", span("Select ID No. :",class="sidebar-label"), min = min(simulated_sdata$id), max = 100, value = 50)
      ),

      conditionalPanel(
        condition = "input.data_option_page4== 'default' & input.Bigdata_page4=='Yes'",
        sliderInput("pidBIG_page4", span("Select ID No. :",class="sidebar-label"), min = min(new_surv2$id), max = 600, value = 50)
      ),


      conditionalPanel(
        condition = "input.data_option_page4 == 'upload'",
        fileInput("lfile_page4", span("Upload Longitudinal Data (CSV format)",class="sidebar-label")),
        fileInput("sfile_page4", span("Upload Survival Data (CSV format)",class="sidebar-label")),
        uiOutput("pid_slider_upload_page4")
      ),
      selectInput("Bigdata_page4", span("Is the sample size geater than 500?",class="sidebar-label"), choices =c("Yes","No")),
      selectInput("idvar_page4", span("ID variable",class="sidebar-label"), choices =NULL),
      selectInput("timevar_page4",span("Visit time",class="sidebar-label"), choices = NULL),


      textInput("longmodel1_page4", span("Longitudinal data model (For event 1)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel1_page4", span("Longitudinal data model random effect part (For event 1)",class="sidebar-label"), value = "~visit|id"),

      textInput("longmodel2_page4",span("Longitudinal data model (For event 2)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel2_page4", span("Longitudinal data model random effect part (For event 2)",class="sidebar-label"), value = "~visit|id"),
      textInput("survmodel1_page4", span("Survival data model (For event 1)",class="sidebar-label"), value = "Surv(time,status)~x1+visit"),
      textInput("survmodel2_page4", span("Survival data model (For event 2)",class="sidebar-label"), value = "Surv(time_2,status_2)~x1+visit"),
      textInput("time_points1_page4",span("Time points for plot (event 1):",class="sidebar-label"),value=4),
      textInput("time_points2_page4",span("Time points for plot (event 2):",class="sidebar-label"),value=9),
      #selectInput("Bigdata_page4", "Is it BIG data", choices =c("Yes","No")),
      numericInput("samplesize_page4", span("Loop size",class="sidebar-label"), value = 200),
      actionButton("submit_page4", span("Submit",class="submit_page4"))
    ),

    mainPanel(
      # div(
      #   class = "gif-container",
      #   tags$img(src = "jmbdirect_animation.gif", width = "500px", height = "500px")
      # ),
      #imageOutput("image_output_page4"),
      p('jmrmlB(): a function for joint model in small data as well as BIG DATA using JoineR, jmBIG package. For more information about the arguments of the function please look ',a("here.",href = "https://cran.r-project.org/web/packages/JMbdirect/index.html")),
      div(
           style = "margin-left: 90px; text-align: center;",
          h6(
            "Fig: The figure shows the longitudinal and survival plots", br(),
            "for Subject ID: 1 to 100",
            style = "color: darkred; font-weight: bold; font-style: italic;"
          ),
          imageOutput("image_output_page4"),
          
        ),
      h4(strong("An example R Code for the model:"),class="summary-text"),
      div(class = "custom-text-output",uiOutput("rCode_page4")),
      h4(strong("Model summary:"),class="summary-text"),
      div(verbatimTextOutput("summarymodel_page4"),class = "custom-text-output"),
      h4(strong("Selected ID information:"),class="summary-text"),
      div(textOutput("selected_var_page4"),class= "custom-text-output"),
      div(dataTableOutput('longID_page4'),class="custom-text-output"),
      h4(strong("Plot for the selected ID:"),class="summary-text"),
      div(textOutput("selectedID_page4"),class="custom-text-output"),
      shinycssloaders::withSpinner(plotOutput("summaryplot_page4"))
    )
  )
),

server_page4<-function(input, output, session){

  temp_file <- tempfile(fileext = ".gif")
  
  # Step 2: Download the file from Google Drive
  gif_url <- "https://drive.google.com/uc?id=1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3"
  
  download.file(gif_url, temp_file, mode = "wb")  # Save as binary file
  output$image_output_page4 <- renderImage({
    list(
      src = temp_file,
      contentType = "image/gif",
      width = 410,
      height = 350
    )
  }, deleteFile = FALSE)  # Don't delete immediately, we'll do it manually

  
  
  
  output$rCode_page4 <- renderText({
HTML("model_joinrml<-jmrmlB(dtlong=...,dtsurv=...,<br>
longm=list(serBilir~drug*year,albumin~drug+year),<br>
survm=list(Surv(years,status2)~drug,Surv(time_2,status_2)~drug),<br>
rd=list(~year|id,~year|id),timeVar='year',id='id')<br><br>
<b>Here is the list of entries in side bar panel according to this example(default small data):</b><br>
ID variable: id<br>
Visit time: year<br>
Longitudinal data model (For event 1): serBilir~drug*year<br>
Longitudinal data model random effect part (For event 1): ~year|id<br>
Longitudinal data model (For event 2): albumin~drug+year<br>
Longitudinal data model random effect part (For event 2): ~year|id<br>
Survival data model (For event 1): Surv(years,status2)~drug<br>
Survival data model (For event 2): Surv(time_2,status_2)~drug<br>
Time points for plot (event 1): 6<br>
Time points for plot (event 2): 10<br>
Is it BIG data: No<br>
Loop size: 200(default you may use other also)")
  })


  defaultsurvdata_page4 <- reactive({
    if (input$data_option_page4 == 'upload') {
      req(input$sfile_page4)
      defaultsurvdata_page4 <- read.csv(input$sfile_page4$datapath)
    } else {
      if(input$Bigdata_page4=="Yes"){
        defaultsurvdata_page4 <- new_surv2[new_surv2$id<=600,]
      }else{
        defaultsurvdata_page4 <- simulated_sdata
      }
    }
    return(defaultsurvdata_page4)
  })


  observeEvent(defaultsurvdata_page4(), {
    updateSelectInput(session, "idvar_page4", choices = names(defaultsurvdata_page4()))
    updateSelectInput(session, "timevar_page4", choices = names(defaultsurvdata_page4()))
    updateSelectInput(session, "event_page4", choices = names(defaultsurvdata_page4()))
    updateSelectInput(session, "obs_time_page4", choices = names(defaultsurvdata_page4()))
  })



  defaultlongdata_page4 <- reactive({
    if (input$data_option_page4 == 'upload') {
      req(input$lfile_page4)
      defaultlongdata_page4 <- read.csv(input$lfile_page4$datapath)
    } else {

      if(input$Bigdata_page4=="Yes"){
        defaultlongdata_page4 <- new_long2[new_long2$id<=600,]
      }else{
        defaultlongdata_page4 <- simulated_ldata
      }
    }
    return(defaultlongdata_page4)
  })


  output$pid_slider_upload_page4 <- renderUI({
    req(input$idvar_page4)
    tagList(
      selectInput("pid_page44", "Patient ID", choices=defaultsurvdata_page4()[[input$idvar_page4]],selectize = FALSE,size=5)
    )
  })

  output$selected_var_page4 <- reactive({

    if (input$data_option_page4 == "default") {
      req(input$Bigdata_page4)
      if(input$Bigdata_page4=="Yes"){
        req(input$pidBIG_page4)
        paste("You have selected patient ID", input$pidBIG_page4)
      }else{
        paste("You have selected patient ID", input$pid_page4)
      }
    } else {
      req(input$pid_page44)
      paste("Uploaded data selected with patient ID",input$pid_page44)
    }
  })

  output$selectedID_page4 <- reactive({

    if (input$data_option_page4 == "default") {
      req(input$pid_page4)
      req(input$Bigdata_page4)
      if(input$Bigdata_page4=="No"){
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmrmlB() for the selected patient ID: ',input$pid_page4)
      }else{
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmrmlB() for the selected patient ID: ',input$pidBIG_page4)
      }
      } else {
      req(input$pid_page44)
      paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmrmlB() for the selected patient ID: ',input$pid_page44)
    }
  })

rv<-reactiveValues(model_page4=NULL,idnum_page4=NULL)

longID_page4 <- reactive({

    if (input$data_option_page4 == "default") {
      req(input$pid_page4)
      req(input$timevar_page4)
      req(input$idvar_page4)
      req(input$Bigdata_page4)
      req(defaultlongdata_page4())
      req(defaultsurvdata_page4())

      surv_var1_page4<-all.vars(as.formula(input$survmodel1_page4))
      surv_var2_page4<-all.vars(as.formula(input$survmodel2_page4))
      surv_status1_page4<-surv_var1_page4[2]
      surv_status2_page4<-surv_var2_page4[2]
      surv_time1_page4<-surv_var1_page4[1]
      surv_time2_page4<-surv_var2_page4[1]

      long_data_page4<-defaultlongdata_page4()
      surv_data_page4<-defaultsurvdata_page4()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page4<-if(input$Bigdata_page4=='No'){input$pid_page4}else{input$pidBIG_page4}

      newdata_page4<-long_data_page4[long_data_page4[[input$idvar_page4]]==rv$idnum_page4,]
      # paste('Survival and longitudinal information for the selected patient ID: ',rv$idnum_page4)
      # paste(
      #   "Survival time for Event 1 is",unique(newdata_page4[[surv_time1_page4]]), ";",
      #   "Survival time for Event 2 is",unique(newdata_page4[[surv_time2_page4]]), ";",
      #   "Time variable range is", min(newdata_page4[[input$timevar_page4]]), round(max(newdata_page4[[input$timevar_page4]]),2))
      newdata_page4
    } else {
      req(input$timevar_page4)
      req(input$idvar_page4)
      req(defaultlongdata_page4())
      req(defaultsurvdata_page4())
      req(input$pid_page44)
      #paste('Survival and longitudinal information for the selected patient ID: ',input$pid_page22)
      surv_var1_page4<-all.vars(as.formula(input$survmodel1_page4))
      surv_var2_page4<-all.vars(as.formula(input$survmodel2_page4))
      surv_status1_page4<-surv_var1_page4[2]
      surv_status2_page4<-surv_var2_page4[2]
      surv_time1_page4<-surv_var1_page4[1]
      surv_time2_page4<-surv_var2_page4[1]

      long_data_page4<-defaultlongdata_page4()
      surv_data_page4<-defaultsurvdata_page4()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page4<-input$pid_page44
      newdata_page4<-long_data_page4[long_data_page4[[input$idvar_page4]]==input$pid_page44,]
      # paste('Survival and longitudinal information for the selected patient ID: ',input$pid_page4)
      # paste(
      #   "Survival time for Event 1 is",unique(newdata_page4[[surv_time1_page4]]), ";",
      #   "Survival time for Event 2 is",unique(newdata_page4[[surv_time2_page4]]), ";",
      #   "Time variable range is", min(newdata_page4[[input$timevar_page4]]), round(max(newdata_page4[[input$timevar_page4]]),2))
      newdata_page4
    }
  })

observeEvent(input$submit_page4, {
  output$longID_page4 <- DT::renderDT({
    data_page4 <- as.data.frame(longID_page4())

    # Round numeric columns to 1 decimal place
    numeric_cols <- sapply(data_page4, is.numeric)
    data_page4[numeric_cols] <- lapply(data_page4[numeric_cols], round, 1)

    DT::datatable(data_page4,
                  options = list(
                    pageLength = 5,
                    autoWidth = TRUE,
                    dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),  # Export options
                    scrollX = TRUE,  # Enable horizontal scrolling
                    scrollY = "400px",
                    scrollCollapse = TRUE,# Enable vertical scrolling with fixed height
                    paging = TRUE  # Keep pagination enabled
                  ),
                  class = "cell-border stripe hover",
                  width = "100%",  # Adjust table width
                  height = "500px"  # Adjust table height
    ) %>%
      DT::formatStyle(
        columns = names(data_page4),
        color = "black",
        backgroundColor = "#f0f8ff",  # Light blue
        fontSize = '10px'  # Change font size
      )
  })
})


  #rv<-reactiveValues(model_page4=NULL)

  observeEvent(input$submit_page4,{
    output$summarymodel_page4 <- renderPrint({
      req(input$longmodel1_page4)
      req(input$longmodel2_page4)
      req(input$rdmodel1_page4)
      req(input$rdmodel2_page4)
      req(input$survmodel1_page4)
      req(input$survmodel2_page4)
      req(input$timevar_page4)
      req(input$idvar_page4)
      req(input$Bigdata_page4)
      req(defaultlongdata_page4())
      req(defaultsurvdata_page4())

      longmodel1_page4<-as.formula(input$longmodel1_page4)
      rdmodel1_page4<-as.formula(input$rdmodel1_page4)
      longmodel2_page4<-as.formula(input$longmodel2_page4)
      rdmodel2_page4<-as.formula(input$rdmodel2_page4)
      survmodel1_page4<-as.formula(input$survmodel1_page4)
      survmodel2_page4<-as.formula(input$survmodel2_page4)
      BIGdata_t<-ifelse(input$Bigdata_page4=="Yes",TRUE,FALSE)
      long_data_page4<-defaultlongdata_page4()
      surv_data_page4<-defaultsurvdata_page4()

      fitmodel_page44 <-jmrmlB(dtlong=long_data_page4,
                               dtsurv=surv_data_page4,
                               longm=list(longmodel1_page4,longmodel2_page4),
                               survm=list(survmodel1_page4, survmodel2_page4),
                               rd=list(rdmodel1_page4,rdmodel2_page4),
                               timeVar=input$timevar_page4,
                               samplesize =200,
                               BIGdata=BIGdata_t,
                               id=input$idvar_page4)
      #fitmodel_page44<-survmodel1_page4
      rv$model_page4<-fitmodel_page44
      fitmodel_page44

    })
  })

  observeEvent(input$submit_page4,{
    output$summaryplot_page4<- renderPlot({
      req(input$timevar_page4)
      req(input$idvar_page4)
      #req(input$pid_page4)
      #req(input$time_points_page2)
      req(defaultlongdata_page4())
      req(defaultsurvdata_page4())
      req(input$time_points1_page4)
      req(input$time_points2_page4)

      surv_var1_page4<-all.vars(as.formula(input$survmodel1_page4))
      surv_var2_page4<-all.vars(as.formula(input$survmodel2_page4))
      surv_status1_page4<-surv_var1_page4[2]
      surv_status2_page4<-surv_var2_page4[2]
      surv_time1_page4<-surv_var1_page4[1]
      surv_time2_page4<-surv_var2_page4[1]

      long_data_page4<-defaultlongdata_page4()
      surv_data_page4<-defaultsurvdata_page4()
      time_point1_page4<-input$time_points1_page4
      time_point2_page4<-input$time_points2_page4

      newdata_page4<-long_data_page4[long_data_page4[[input$idvar_page4]]==rv$idnum_page4,]
      newdata_page4<-newdata_page4[newdata_page4[[input$timevar_page4]]<time_point1_page4,]
      newdata_page4[[surv_status1_page4]]<-0
      newdata_page4[[surv_time1_page4]]<-time_point1_page4
      newdata_page4[[surv_time2_page4]]<-time_point2_page4
      newdata_page4[[surv_status2_page4]]<-0

      newdata_page4[[input$timevar_page4]]<-as.numeric(as.character(newdata_page4[[input$timevar_page4]]))
      newdata_page4[[surv_time1_page4]]<-as.numeric(as.character(newdata_page4[[surv_time1_page4]]))
      newdata_page4[[surv_time2_page4]]<-as.numeric(as.character(newdata_page4[[surv_time2_page4]]))

      #summary(newdata_page4)
      #plot(rv$model_page2,newdata_page2)
      #############################################################################
      x<-rv$model_page4
      y<-newdata_page4
      result<-x
      model1<-result$model1
      model2<-result$model2
      IDvar<-x$IDvar
      y<-as.data.frame(y)
      newdata<-as.data.frame(y)
      if(result$BIGdata==F){
        longdata1<-model1$data[[1]]
        survdata1<-model1$survData
        longdata2<-model2$data[[1]]
        survdata2<-model2$survData
        surv1_var<-all.vars(x$model1$formSurv)[1]
        surv2_var<-all.vars(x$model2$formSurv)[1]
        long_var1<-all.vars(model1$formLongFixed[[1]])
        time_var1<-model1$timeVar
        long_var2<-all.vars(model2$formLongFixed[[1]])
        time_var2<-model2$timeVar
        names(longdata1)[which(names(longdata1)==model1$id)]<-'id'
        names(longdata2)[which(names(longdata2)==model2$id)]<-'id'
        names(newdata)[which(names(newdata)==IDvar)]<-'id'
        ID<-unique(newdata$id)
        ydata_1<-newdata
        ydata_2<-newdata
        t_0<-unique(newdata[,surv1_var])
        t_1<-unique(newdata[,surv2_var])
        pred_long1<-data.frame(dynLong(model1,newdata=newdata)[[1]])
        pred_long2<-data.frame(dynLong(model2,newdata=newdata)[[1]])
        if(t_0<=t_1){
          pred_surv1<-dynSurv(model1,newdata=newdata,type='simulated',u=seq(t_0,t_1,length.out=20))
          pred_surv1<-pred_surv1$pred
          pred_surv2<-dynSurv(model2,newdata=newdata,type='simulated',u=seq(t_1,2*t_1,length.out=20))
          pred_surv2<-pred_surv2$pred
        }else{
          pred_surv1<-dynSurv(model2,newdata=newdata,type='simulated',u=seq(t_1,t_0,length.out=20))
          pred_surv1<-pred_surv1$pred
          pred_surv2<-dynSurv(model1,newdata=newdata,type='simulated',u=seq(t_0,2*t_0,length.out=20))
          pred_surv2<-pred_surv2$pred
        }
        names(ydata_1)[which(names(ydata_1)==long_var1[[1]])]<-'y.value1'
        names(ydata_2)[which(names(ydata_2)==long_var2[[1]])]<-'y.value2'
        names(ydata_1)[which(names(ydata_1)==time_var1)]<-'Time'
        names(ydata_2)[which(names(ydata_2)==time_var1)]<-'Time'

      }else{
        longdata1<-list()
        for(i in 1:length(x$model1$allmodel)){
          longdata1[[i]]<-as.data.frame(x$model1$allmodel[[i]]$data)
        }
        longdata1<-Reduce('rbind',longdata1)
        survdata1<-list()
        for(i in 1:length(x$model1$allmodel)){
          survdata1[[i]]<-as.data.frame(x$model1$allmodel[[i]]$survData)
        }
        survdata1<-Reduce('rbind',survdata1)
        longdata2<-list()
        for(i in 1:length(x$model2$allmodel)){
          longdata2[[i]]<-as.data.frame(x$model2$allmodel[[i]]$data)
        }
        longdata2<-Reduce('rbind',longdata2)
        survdata2<-list()
        for(i in 1:length(x$model2$allmodel)){
          survdata2[[i]]<-as.data.frame(x$model2$allmodel[[i]]$survData)
        }
        survdata2<-Reduce('rbind',survdata2)
        surv1_var<-all.vars(x$model1$pseudoMod$formSurv)[1]
        surv2_var<-all.vars(x$model2$pseudoMod$formSurv)[1]
        long_var1<-all.vars(x$model1$pseudoMod$formLongFixed[[1]])[1]
        time_var1<-x$model1$pseudoMod$timeVar
        long_var2<-all.vars(x$model2$pseudoMod$formLongFixed[[1]])[1]
        time_var2<-x$model2$pseudoMod$timeVar
        names(longdata1)[which(names(longdata1)==model1$id)]<-'id'
        names(longdata2)[which(names(longdata2)==model2$id)]<-'id'
        names(newdata)[which(names(newdata)==IDvar)]<-'id'
        ID<-unique(newdata$id)
        ydata_1<-newdata
        ydata_2<-newdata
        t_0<-unique(newdata[,surv1_var])
        t_1<-unique(newdata[,surv2_var])
        if(t_0<=t_1){
          pred_ls1<-predJRML(model=x$model1,ids=ID,dtlong=longdata1,dtsurv = survdata1,u=seq(t_0,t_1,length.out=20))
          pred_long1<-pred_ls1$plong[[1]]$pred
          pred_surv1<-pred_ls1$psurv[[1]]$pred
          pred_ls2<-predJRML(model=x$model2,ids=ID,dtlong=longdata2,dtsurv = survdata2,u=seq(t_1,2*t_1,length.out=20))
          pred_long2<-pred_ls2$plong[[1]]$pred
          pred_surv2<-pred_ls2$psurv[[1]]$pred
        }else{
          pred_ls1<-predJRML(model=x$model2,ids=ID,dtlong=longdata2,dtsurv = survdata2,u=seq(t_1,t_0,length.out=20))
          pred_long1<-pred_ls1$plong[[1]]$pred
          pred_surv1<-pred_ls1$psurv[[1]]$pred
          pred_ls2<-predJRML(model=x$model1,ids=ID,dtlong=longdata1,dtsurv = survdata1,u=seq(t_0,2*t_0,length.out=20))
          pred_long2<-pred_ls2$plong[[1]]$pred
          pred_surv2<-pred_ls2$psurv[[1]]$pred
        }
        names(ydata_1)[which(names(ydata_1)==long_var1[[1]])]<-'y.value1'
        names(ydata_2)[which(names(ydata_2)==long_var2[[1]])]<-'y.value2'
        names(ydata_1)[which(names(ydata_1)==time_var1)]<-'Time'
        names(ydata_2)[which(names(ydata_2)==time_var1)]<-'Time'
      }
      K<-2
      m<-cbind(1:K,rep(1+K,K),rep(K+2,K))
      widths<-c(0.3,0.35,0.35)
      layout(m,widths=widths)
      xticks<-pretty(c(ydata_1$Time,ydata_2$Time))
      par(mar=c(0,4.5,0,0),oma=c(4,0,3,0),cex.axis=1.1,font.axis=2,font.lab=2,font.main=2)
      plot(x=ydata_1$Time,y=ydata_1$y.value1,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=ydata_1$Time,y=ydata_1$y.value1,pch=8,col='red')
      mtext(long_var1[1],line=2.5,side=2,font=2)
      box(lwd=1.3)
      par(mar=c(0,4.5,0,0))
      plot(x=ydata_2$Time,y=ydata_2$y.value2,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=ydata_2$Time,y=ydata_2$y.value2,pch=8,col='red')
      mtext(long_var2[1],line=2.5,side=2,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      xticks<-pretty(c(pred_surv1$u))
      par(mar=c(0,0,0,0))
      plot(x=pred_surv1$u,y=pred_surv1$mean,col='black',type='l',las=1,yaxt='n',xaxt='n',xaxs='i',ylab='',ylim=c(0,1),font=2)
      polygon(c(pred_surv1$u,rev(pred_surv1$u)),c(pred_surv1$upper,rev(pred_surv1$lower)),col=rgb(0,0,0.6,0.4),border=NA)
      lines(x=pred_surv1$u,y=pred_surv1$mean,col='blue',lwd=2)
      text(x=median(pred_surv1$u),y=0.99,labels =ifelse(t_0<=t_1,"Event 1","Event 2"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      par(mar=c(0,0,0,4.5))
      xticks<-pretty(c(pred_surv2$u))
      plot(x=pred_surv2$u,y=pred_surv2$mean,col='black',type='l',las=1,yaxt='n',xaxt='n',xaxs='i',ylab='',ylim=c(0,1))
      polygon(c(pred_surv2$u,rev(pred_surv2$u)),c(pred_surv2$upper,rev(pred_surv2$lower)),col=rgb(0.6,0,0.6,0.4),border = NA)
      lines(x=pred_surv2$u,y=pred_surv2$mean,col='red',lwd=2)
      text(x=median(pred_surv2$u),y=0.99,labels =ifelse(t_0<=t_1,"Event 2","Event 1"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      axis(4,las=1)
      mtext('Plot for Bidirectional survival data', 3,
            line = 1, outer = TRUE, font = 2, cex = 1.3)
      mtext("Time", 1,
            line = 2.5, outer = TRUE,font=2)
      mtext("Survival Prediction", 4,
            line = 2.5,font=2)
      box(lwd=1.3)

      ##########################################################################
      ###########################################################################
    })
  })
  
  # Step 4: Delete the file when the session ends
  session$onSessionEnded(function() {
    if (file.exists(temp_file)) {
      file.remove(temp_file)
    }
  })
}
, 
options = list(height=1000,width="100%")
)

```


jmstB 
=====================================  
  
Column {data-width=1000}
-------------------------------------
```{r}
shinyApp(
ui_page5<-fluidPage(
  tags$style(HTML("
    /* Change entire page background */
    body { background-color: #f0f8ff; } /* Light blue */

    /* Style for the main title */
    .main-title { color: darkblue; font-size: 28px; font-weight: bold; text-align: center; }

    /* Styling for different text elements */
    .summary-text { color: blue; }
    .plot-title { color: darkred; font-size: 20px; font-weight: bold; }

    /* Change color of sidebar panel text */
    .sidebar-label { color: blue; font-weight: bold; }

    /* Change color of all sidebar input labels */
    .control-label, .shiny-options-group label { color: darkred; font-size: 16px; font-weight: bold; }

    /* Style for select input dropdown */
    .sidebar-input select { color: darkgreen; font-weight: bold; }

    /* Change color of action button text */
    #submit_page5 { background-color: white; color: red; border: 2px solid red; font-weight: bold; }

    /* OPTIONAL: Add hover effect to the submit button */
    #submit_page5:hover { background-color: red; color: white; }

    /* Customize sidebar background */
    .well { background-color: #e6f2ff; border-radius: 10px; } /* Light blue */

    /* Customize main panel background */
    .main-panel { background-color: #ffffff; padding: 20px; border-radius: 10px; }

      .custom-text-output {
      color: rgb(0, 70, 0);  /* Change text color */
      font-size: 15px;   /* Adjust font size */
      font-family: 'Times New Roman', Times, serif;/* Use monospace font */
      background-color: #f4f4f4; /* Light gray background */
      padding: 10px; /* Add padding */
      border-radius: 5px; /* Rounded corners */
      }
    /* Change text color inside text input fields */
    .form-control {
      color: darkred !important; /* Change text color */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Change text color inside all selectInput dropdowns */
    .selectize-input {
      color: darkred !important;  /* Change dropdown text color */
      font-weight: bold !important;
      font-size: 16px !important;
      /*background-color: lightgray !important;  Change background */
      /*border: 2px solid red !important;   Change border color */
    }

    /* Change text color inside the dropdown list */
    .selectize-dropdown-content {
      color: darkred !important; /* Change dropdown option text */
      font-weight: bold !important;
      font-size: 16px !important;
    }

    /* Hover effect for dropdown options */
    .selectize-dropdown-content .option:hover {
      background-color: yellow !important;  /* Change hover background */
      color: black !important;  /* Change text color on hover */
    }

    /* Custom styling for the DT table */
    .styled-table .dataTable {
        border-collapse: collapse;
        width: 40%;
        font-size: 6px;
        border: 1px solid #ddd;
    }

    /* Header styling */
    .styled-table .dataTable thead {
        background-color: darkblue;
        color: white;
    }

    /* Row hover effect */
    .styled-table .dataTable tbody tr:hover {
        background-color: #e6f2ff; /* Light blue */
    }

    /* Border for table */
    .styled-table .dataTable tbody td {
        border: 1px solid #ddd;
        padding: 5px;
    }

    .gif-container {
  display: flex;
  justify-content: flex-end; /* Center horizontally */
  align-items: center; /* Center vertically (if needed) */
  margin-top: 20px;
  padding: 10px; /* Add some space inside */
  border: 3px solid #3498db; /* Blue border */
  border-radius: 10px; /* Rounded corners */
  background-color: #f9f9f9; /* Light background */
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1); /* Soft shadow */
  width: 420px; /* Box width slightly larger than GIF */
  height: 410px; /* Box height */
}

.gif-container img {
  width: 400px;  /* Adjust size */
  height: auto;
}
")),
  titlePanel(tags$h1("Joint Model for longitudinal and multiple time-to-events data using jmstB() function",class="main-title")),
  sidebarLayout(
    sidebarPanel(
      radioButtons("data_option_page5", span("Select data source:",class="sidebar-label"),
                   c("Upload my own dataset" = "upload",
                     "Use default dataset" = "default")),
      conditionalPanel(
        condition = "input.data_option_page5== 'default' & input.Bigdata_page5=='No'",
        sliderInput("pid_page5", span("Select ID No. :",class="sidebar-label"), min = min(simulated_sdata$id), max = 100, value = 50)
      ),

      conditionalPanel(
        condition = "input.data_option_page5== 'default' & input.Bigdata_page5=='Yes'",
        sliderInput("pidBIG_page5", span("Select ID No. :",class="sidebar-label"), min = min(new_surv2$id), max = 600, value = 50)
      ),


      conditionalPanel(
        condition = "input.data_option_page5 == 'upload'",
        fileInput("lfile_page5", span("Upload Longitudinal Data (CSV format)",class="sidebar-label")),
        fileInput("sfile_page5", span("Upload Survival Data (CSV format)",class="sidebar-label")),
        uiOutput("pid_slider_upload_page5")
      ),
      selectInput("Bigdata_page5", span("Is the sample size geater than 500?",class="sidebar-label"), choices =c("Yes","No")),
      selectInput("idvar_page5", span("ID variable",class="sidebar-label"), choices =NULL),
      selectInput("timevar_page5", span("Visit time",class="sidebar-label"), choices = NULL),


      textInput("longmodel1_page5", span("Longitudinal data model (For event 1)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel1_page5", span("Longitudinal data model random effect part (For event 1)",class="sidebar-label"), value = "~visit|id"),

      textInput("longmodel2_page5", span("Longitudinal data model (For event 2)",class="sidebar-label"), value = "y~1+x7"),
      textInput("rdmodel2_page5", span("Longitudinal data model random effect part (For event 2)",class="sidebar-label"), value = "~visit|id"),
      textInput("survmodel1_page5",  span("Survival data model (For event 1)",class="sidebar-label"), value = "Surv(time,status)~x1+visit"),
      textInput("survmodel2_page5",span("Survival data model (For event 2)",class="sidebar-label"), value = "Surv(time_2,status_2)~x1+visit"),
      textInput("time_points1_page5",span("Time points for plot (event 1):",class="sidebar-label"),value=4),
      textInput("time_points2_page5",span("Time points for plot (event 2):",class="sidebar-label"),value=9),
      numericInput("nchain_page5", span("Number of chain for MCMC",class="sidebar-label"), value = 1),
      #selectInput("Bigdata_page5", "Is it BIG data", choices =c("Yes","No")),
      numericInput("samplesize_page5", span("Loop size",class="sidebar-label"), value = 200),
      actionButton("submit_page5", span("Submit",class="submit_page5"))
    ),

    mainPanel(
      # div(
      #   class = "gif-container",
      #   tags$img(src = "jmbdirect_animation.gif", width = "500px", height = "500px")
      # ),
      #imageOutput("image_output_page5"),
      p('jmstB(): a function for joint model in small data as well as BIG DATA using rstanarm, jmBIG package. For more information about the arguments of the function please look ',a("here.",href = "https://cran.r-project.org/web/packages/JMbdirect/index.html")),
      div(
           style = "margin-left: 90px; text-align: center;",
          h6(
            "Fig: The figure shows the longitudinal and survival plots", br(),
            "for Subject ID: 1 to 100",
            style = "color: darkred; font-weight: bold; font-style: italic;"
          ),
          imageOutput("image_output_page5"),
          
        ),
      h4(strong("An example R Code for the model:"),class="summary-text"),
      div(class = "custom-text-output",uiOutput("rCode_page5")),
      h4(strong("Model summary:"),class="summary-text"),
      div(verbatimTextOutput("summarymodel_page5"),class = "custom-text-output"),
      h4(strong("Selected ID information:"),class="summary-text"),
      div(textOutput("selected_var_page5"),class= "custom-text-output"),
      div(dataTableOutput('longID_page5'),class="custom-text-output"),
      h4(strong("Plot for the selected ID:"),class="summary-text"),
      div(textOutput("selectedID_page5"),class="custom-text-output"),
      shinycssloaders::withSpinner(plotOutput("summaryplot_page5"))
    )
  )
),
  
server_page5<-function(input, output, session){
  
  temp_file <- tempfile(fileext = ".gif")
  
  # Step 2: Download the file from Google Drive
  gif_url <- "https://drive.google.com/uc?id=1Vi-SWy9GwN2P8zjvaigsm5aYAcePlqL3"
  
  download.file(gif_url, temp_file, mode = "wb")  # Save as binary file
  output$image_output_page5 <- renderImage({
    list(
      src = temp_file,
      contentType = "image/gif",
      width = 410,
      height = 350
    )
  }, deleteFile = FALSE)  # Don't delete immediately, we'll do it manually


output$rCode_page5 <- renderUI({
HTML("model_jmstBdirect<-jmstB(dtlong=...,dtsurv =...,<br>
longm=list(serBilir~drug*year+(year|id),albumin~drug+year+(year|id)),<br>
survm=list(Surv(years,status2)~drug,Surv(time_2,status_2)~drug),<br>
timeVar='year',id='id',refresh=400,nchain=1)<br><br>
<b>Here is the list of entries in side bar panel according to this example(default small data):</b><br>
ID variable: id<br>
Visit time: year<br>
Longitudinal data model (For event 1): serBilir~drug*year<br>
Longitudinal data model random effect part (For event 1): ~(year|id)<br>
Longitudinal data model (For event 2): albumin~drug+year<br>
Longitudinal data model random effect part (For event 2): ~(year|id)<br>
Survival data model (For event 1): Surv(years,status2)~drug<br>
Survival data model (For event 2): Surv(time_2,status_2)~drug<br>
Time points for plot (event 1): 6<br>
Time points for plot (event 2): 10<br>
Is it BIG data: No<br>
Loop size: 200(default you may use other also)")
  })


  defaultsurvdata_page5 <- reactive({
    if (input$data_option_page5 == 'upload') {
      req(input$sfile_page5)
      defaultsurvdata_page5 <- read.csv(input$sfile_page5$datapath)
    } else {
      if(input$Bigdata_page5=="Yes"){
        defaultsurvdata_page5 <- new_surv2[new_surv2$id<=600,]
      }else{
        defaultsurvdata_page5 <- simulated_sdata
      }
    }
    return(defaultsurvdata_page5)
  })


  observeEvent(defaultsurvdata_page5(), {
    updateSelectInput(session, "idvar_page5", choices = names(defaultsurvdata_page5()))
    updateSelectInput(session, "timevar_page5", choices = names(defaultsurvdata_page5()))
    updateSelectInput(session, "event_page5", choices = names(defaultsurvdata_page5()))
    updateSelectInput(session, "obs_time_page5", choices = names(defaultsurvdata_page5()))
  })



  defaultlongdata_page5 <- reactive({
    if (input$data_option_page5 == 'upload') {
      req(input$lfile_page5)
      defaultlongdata_page5 <- read.csv(input$lfile_page5$datapath)
    } else {

      if(input$Bigdata_page5=="Yes"){
        defaultlongdata_page5 <- new_long2[new_long2$id<=600,]
      }else{
        defaultlongdata_page5 <- simulated_ldata
      }
    }
    return(defaultlongdata_page5)
  })


  output$pid_slider_upload_page5 <- renderUI({
    req(input$idvar_page5)
    tagList(
      selectInput("pid_page55", "Patient ID", choices=defaultsurvdata_page5()[[input$idvar_page5]],selectize = FALSE,size=5)
    )
  })

  output$selected_var_page5 <- reactive({

    if (input$data_option_page5 == "default") {
      req(input$Bigdata_page5)
      if(input$Bigdata_page5=="Yes"){
        req(input$pidBIG_page5)
        paste("You have selected patient ID", input$pidBIG_page5)
      }else{
        paste("You have selected patient ID", input$pid_page5)
      }
    } else {
      req(input$pid_page55)
      paste("Uploaded data selected with patient ID",input$pid_page55)
    }
  })

  output$selectedID_page5 <- reactive({

    if (input$data_option_page5 == "default") {
      req(input$pid_page5)
      req(input$Bigdata_page5)
      if(input$Bigdata_page5=="No"){
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmstB() for the selected patient ID: ',input$pid_page5)
      }else{
        paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmstB() for the selected patient ID: ',input$pidBIG_page5)
      }
      } else {
      req(input$pid_page55)
      paste('Prediction of survival probability and longitudinal marker learned from model fitted using jmstB() for the selected patient ID: ',input$pid_page55)
    }
  })

  rv<-reactiveValues(model_page5=NULL,idnum_page5=NULL)
  longID_page5 <- reactive({

    if (input$data_option_page5 == "default") {
      req(input$pid_page5)
      req(input$timevar_page5)
      req(input$idvar_page5)
      req(input$Bigdata_page5)
      req(defaultlongdata_page5())
      req(defaultsurvdata_page5())

      surv_var1_page5<-all.vars(as.formula(input$survmodel1_page5))
      surv_var2_page5<-all.vars(as.formula(input$survmodel2_page5))
      surv_status1_page5<-surv_var1_page5[2]
      surv_status2_page5<-surv_var2_page5[2]
      surv_time1_page5<-surv_var1_page5[1]
      surv_time2_page5<-surv_var2_page5[1]

      long_data_page5<-defaultlongdata_page5()
      surv_data_page5<-defaultsurvdata_page5()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page5<-if(input$Bigdata_page5=='No'){input$pid_page5}else{input$pidBIG_page5}

      newdata_page5<-long_data_page5[long_data_page5[[input$idvar_page5]]==rv$idnum_page5,]
      newdata_page5

    } else {
      req(input$timevar_page5)
      req(input$idvar_page5)
      req(defaultlongdata_page5())
      req(defaultsurvdata_page5())
      req(input$pid_page55)
      #paste('Survival and longitudinal information for the selected patient ID: ',input$pid_page22)
      surv_var1_page5<-all.vars(as.formula(input$survmodel1_page5))
      surv_var2_page5<-all.vars(as.formula(input$survmodel2_page5))
      surv_status1_page5<-surv_var1_page5[2]
      surv_status2_page5<-surv_var2_page5[2]
      surv_time1_page5<-surv_var1_page5[1]
      surv_time2_page5<-surv_var2_page5[1]

      long_data_page5<-defaultlongdata_page5()
      surv_data_page5<-defaultsurvdata_page5()
      #time_point1_page2<-input$time_points1_page2
      #time_point2_page2<-input$time_points2_page2
      rv$idnum_page5<-input$pid_page55
      newdata_page5<-long_data_page5[long_data_page5[[input$idvar_page5]]==input$pid_page55,]
      newdata_page5
      }
  })

  observeEvent(input$submit_page5, {
    output$longID_page5 <- DT::renderDT({
      data_page5 <- as.data.frame(longID_page5())

      # Round numeric columns to 1 decimal place
      numeric_cols <- sapply(data_page5, is.numeric)
      data_page5[numeric_cols] <- lapply(data_page5[numeric_cols], round, 1)

      DT::datatable(data_page5,
                    options = list(
                      pageLength = 5,
                      autoWidth = TRUE,
                      dom = 'Bfrtip',
                      buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),  # Export options
                      scrollX = TRUE,  # Enable horizontal scrolling
                      scrollY = "400px",
                      scrollCollapse = TRUE,# Enable vertical scrolling with fixed height
                      paging = TRUE  # Keep pagination enabled
                    ),
                    class = "cell-border stripe hover",
                    width = "100%",  # Adjust table width
                    height = "500px"  # Adjust table height
      ) %>%
        DT::formatStyle(
          columns = names(data_page5),
          color = "black",
          backgroundColor = "#f0f8ff",  # Light blue
          fontSize = '10px'  # Change font size
        )
    })
  })

  observeEvent(input$submit_page5,{
    output$summarymodel_page5 <- renderPrint({
      req(input$longmodel1_page5)
      req(input$longmodel2_page5)
      req(input$rdmodel1_page5)
      req(input$rdmodel2_page5)
      req(input$survmodel1_page5)
      req(input$survmodel2_page5)
      req(input$timevar_page5)
      req(input$idvar_page5)
      req(input$Bigdata_page5)
      req(defaultlongdata_page5())
      req(defaultsurvdata_page5())

      longmodel1_page5<-as.formula(input$longmodel1_page5)
      rdmodel1_page5<-as.formula(input$rdmodel1_page5)
      comb_model1_page5<-as.formula(paste(deparse(longmodel1_page5), "+", deparse(rdmodel1_page5[[2]])))

      longmodel2_page5<-as.formula(input$longmodel2_page5)
      rdmodel2_page5<-as.formula(input$rdmodel2_page5)
      comb_model2_page5<-as.formula(paste(deparse(longmodel2_page5), "+", deparse(rdmodel2_page5[[2]])))

      survmodel1_page5<-as.formula(input$survmodel1_page5)
      survmodel2_page5<-as.formula(input$survmodel2_page5)
      BIGdata_t<-ifelse(input$Bigdata_page5=="Yes",TRUE,FALSE)
      long_data_page5<-defaultlongdata_page5()
      surv_data_page5<-defaultsurvdata_page5()

      fitmodel_page55 <-jmstB(dtlong=long_data_page5,
                              dtsurv=surv_data_page5,
                              longm=list(comb_model1_page5,comb_model2_page5),
                              survm=list(survmodel1_page5, survmodel2_page5),
                              timeVar=input$timevar_page5,
                              samplesize =200,
                              BIGdata=BIGdata_t,
                              id=input$idvar_page5,
                              refresh=400,
                              nchain=1)
      #fitmodel_page55<-survmodel1_page5
      rv$model_page5<-fitmodel_page55
      fitmodel_page55

    })
  })

  observeEvent(input$submit_page5,{
    output$summaryplot_page5<- renderPlot({
      req(input$timevar_page5)
      req(input$idvar_page5)
      #req(input$pid_page5)
      #req(input$time_points_page2)
      req(defaultlongdata_page5())
      req(defaultsurvdata_page5())
      req(input$time_points1_page5)
      req(input$time_points2_page5)

      surv_var1_page5<-all.vars(as.formula(input$survmodel1_page5))
      surv_var2_page5<-all.vars(as.formula(input$survmodel2_page5))
      surv_status1_page5<-surv_var1_page5[2]
      surv_status2_page5<-surv_var2_page5[2]
      surv_time1_page5<-surv_var1_page5[1]
      surv_time2_page5<-surv_var2_page5[1]

      long_data_page5<-defaultlongdata_page5()
      surv_data_page5<-defaultsurvdata_page5()
      time_point1_page5<-input$time_points1_page5
      time_point2_page5<-input$time_points2_page5

      newdata_page5<-long_data_page5[long_data_page5[[input$idvar_page5]]==rv$idnum_page5,]
      newdata_page5<-newdata_page5[newdata_page5[[input$timevar_page5]]<time_point1_page5,]
      newdata_page5[[surv_status1_page5]]<-0
      newdata_page5[[surv_time1_page5]]<-time_point1_page5
      newdata_page5[[surv_time2_page5]]<-time_point2_page5
      newdata_page5[[surv_status2_page5]]<-0

      newdata_page5[[input$timevar_page5]]<-as.numeric(as.character(newdata_page5[[input$timevar_page5]]))
      newdata_page5[[surv_time1_page5]]<-as.numeric(as.character(newdata_page5[[surv_time1_page5]]))
      newdata_page5[[surv_time2_page5]]<-as.numeric(as.character(newdata_page5[[surv_time2_page5]]))

      #summary(newdata_page5)
      #plot(rv$model_page2,newdata_page2)
      #############################################################################
      x<-rv$model_page5
      y<-newdata_page5
      result<-x
      model1<-x$model1
      model2<-x$model2
      y<-as.data.frame(y)
      newdata<-y
      IDvar<-x$IDvar
      ID<-as.numeric(unique(y[,IDvar]))
      timeVar<-x$timeVar

      if(result$BIGdata==F){
        first_long<-all.vars(model1$formula$Long1)[1]
        scnd_long<-all.vars(model2$formula$Long1)[1]
        id_var1<-model1$id_var
        id_var2<-model2$id_var
        long1<-model1$dataLong$Long1
        long2<-model2$dataLong$Long1
        surv1_var<-all.vars(model1$formula$Event)[1]
        surv2_var<-all.vars(model2$formula$Event)[1]
        newdata1<-newdata
        newdata2<-newdata
        t_0<-unique(newdata[,surv1_var])
        t_1<-unique(newdata[,surv2_var])
        newLdat<-newdata
        newSdat<-newdata[nrow(newdata),]
        plong1<-posterior_traj(model1,ids=ID)
        if(t_0<=t_1){
          psurv1<-posterior_survfit(model1,extrapolate=TRUE,newdataLong = newLdat,newdataEvent = newSdat,last_time =surv1_var,control=list(epoints=20) )
          psurv2<-posterior_survfit(model2,extrapolate=TRUE,newdataLong = newLdat,newdataEvent = newSdat,last_time =surv2_var,control=list(epoints=20)  )
        }else{
          psurv1<-posterior_survfit(model2,extrapolate=TRUE,newdataLong = newLdat,newdataEvent = newSdat,last_time =surv2_var,control=list(epoints=20)  )
          psurv2<-posterior_survfit(model1,extrapolate=TRUE,newdataLong = newLdat,newdataEvent = newSdat,last_time =surv1_var,control=list(epoints=20)  )

        }
        plong2<-posterior_traj(model2,ids=ID)
        if(t_0<=t_1){
          psurv1<-psurv1[psurv1$year<=t_1,]
          psurv2<-psurv2[psurv2$year<=2*t_1,]
        }else{
          psurv1<-psurv1[psurv1$year<=t_0,]
          psurv2<-psurv2[psurv2$year<=2*t_0,]
        }
        names(newdata1)[which(names(newdata1)==timeVar)]<-'year'
        names(newdata1)[which(names(newdata1)==first_long)]<-'yvalue1'
        names(newdata2)[which(names(newdata2)==timeVar)]<-'year'
        names(newdata2)[which(names(newdata2)==scnd_long)]<-'yvalue2'
      }else{
        first_long<-all.vars(model1$pseudoMod$formula$Long1)[1]
        scnd_long<-all.vars(model2$pseudoMod$formula$Long1)[1]
        id_var1<-model1$pseudoMod$id_var
        id_var2<-model2$pseudoMod$id_var
        surv1_var<-all.vars(model1$pseudoMod$formula$Event)[1]
        surv2_var<-all.vars(model2$pseudoMod$formula$Event)[1]
        newdata1<-newdata
        newdata2<-newdata
        t_0<-as.numeric(unique(newdata[,surv1_var]))
        t_1<-as.numeric(unique(newdata[,surv2_var]))
        newLdat<-newdata
        newSdat<-newdata[nrow(newdata),]
        plong1<-postTraj(model1,m=1,ids=ID)
        if(t_0<=t_1){
          psurv1<-postSurvfit(model1,ids=ID,extrapolate=TRUE,newdataLong = newLdat,
                              newdataEvent = newSdat,last_time =surv1_var,control=list(epoints=20))
          psurv2<-postSurvfit(model2,extrapolate=TRUE,ids=ID,newdataLong=newLdat,
                              newdataEvent=newSdat,last_time=surv2_var,control=list(epoints=20))
        }else{
          psurv1<-postSurvfit(model2,ids=ID,extrapolate=TRUE,newdataLong=newLdat,
                              newdataEvent=newSdat,last_time=surv2_var,control=list(epoints=20))

          psurv2<-postSurvfit(model1,ids=ID,extrapolate=TRUE,newdataLong=newLdat,
                              newdataEvent=newSdat,last_time=surv1_var,control=list(epoints=20))

        }
        plong2<-postTraj(model2,m=1,ids=ID)
        plong1<-plong1$P1
        plong2<-plong2$P1
        psurv1<-psurv1$P1
        names(psurv1)[which(names(psurv1)==timeVar)]<-'year'
        psurv2<-psurv2$P1
        names(psurv2)[which(names(psurv2)==timeVar)]<-'year'
        if(t_0<=t_1){
          psurv1<-psurv1[psurv1$year<=t_1,]
          psurv2<-psurv2[psurv2$year<=2*t_1,]
        }else{
          psurv1<-psurv1[psurv1$year<=t_0,]
          psurv2<-psurv2[psurv2$year<=2*t_0,]
        }
        names(newdata1)[which(names(newdata1)==timeVar)]<-'year'
        names(newdata1)[which(names(newdata1)==first_long)]<-'yvalue1'
        names(newdata2)[which(names(newdata2)==timeVar)]<-'year'
        names(newdata2)[which(names(newdata2)==scnd_long)]<-'yvalue2'

      }

      K<-2
      m<-cbind(1:K,rep(K+1,K),rep(K+2,K))
      xticks<-pretty(c(newdata1$year,newdata2$year))
      widths<-c(0.3,0.35,0.35)
      layout(m,widths=widths)
      par(mar=c(0,4.5,0,0),oma=c(4,0,3,0),cex.axis=1.1,font.axis=2,font.lab=2,font.main=2)
      plot(x=newdata1$year,y=newdata1$yvalue1,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=newdata1$year,y=newdata1$yvalue1,pch=8,col='red')
      mtext(first_long,line=2.5,side=2,font=2)
      box(lwd=1.3)
      par(mar = c(0, 4.5, 0, 0))
      plot(x=newdata2$year,y=newdata2$yvalue2,type='l',las=1,ylab='',xaxt='n',lwd=1.5)
      points(x=newdata2$year,y=newdata2$yvalue2,pch=8,col='red')
      #points(x=newdata2$year,y=newdata2$yvalue2,pch=5,col='green')
      mtext(scnd_long,line=2.5,side=2,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      par(mar=c(0,0,0,0))
      xticks<-pretty(c(psurv1$year))
      plot(x=psurv1$year,y=psurv1$survpred,col='black',type='l',las=1,yaxt='n',xaxt='n',xaxs='i',ylab='',ylim=c(0,1))
      polygon(c(psurv1$year,rev(psurv1$year)),c(psurv1$ci_ub,rev(psurv1$ci_lb)),col=rgb(0,0,0.6,0.4),border=NA)
      lines(x=psurv1$year,y=psurv1$survpred,col='blue',lwd=2)
      text(x=median(psurv1$year),y=0.99,labels = ifelse(t_0<=t_1,"Event 1","Event 2"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      box(lwd=1.3)
      par(mar=c(0,0,0,4.5))
      xticks<-pretty(c(psurv2$year))
      plot(x=psurv2$year,y=psurv2$survpred,col='black',type='l',las=1,yaxt='n',xaxt='n',xaxs='i',ylab='',ylim=c(0,1))
      polygon(c(psurv2$year,rev(psurv2$year)),c(psurv2$ci_ub,rev(psurv2$ci_lb)),col=rgb(0.6,0,0.6,0.4),border = NA)
      lines(x=psurv2$year,y=psurv2$survpred,col='red',lwd=2)
      text(x=median(psurv2$year),y=0.99,labels = ifelse(t_0<=t_1,"Event 2","Event 1"), pos = 3, col = "black", cex = 1.6,font=2)
      axis(1, at = xticks)
      axis(4,las=1)
      mtext('Plot for Bidirectional survival data', 3,
            line = 1, outer = TRUE, font = 2, cex = 1.3)
      mtext("Time", 1,
            line = 2.5, outer = TRUE,font=2)
      mtext("Survival Prediction", 4,
            line = 2.5,font=2)
      box(lwd=1.3)
      ##########################################################################
      ###########################################################################
    })
  })
  # Step 4: Delete the file when the session ends
  session$onSessionEnded(function() {
    if (file.exists(temp_file)) {
      file.remove(temp_file)
    }
  })
}
, 
options = list(height=1000,width="100%")
)

```
